/* AUTO-GENERATED by scripts/build_site.py — do not edit manually. */
window.KB_DATA = {
  "sources": [
    {
      "slug": "ba-xin-xian-gei-hai-zi-zh",
      "title": "把心献给孩子",
      "lang": "ZH",
      "meta": "未知（电子版，对应教育科学出版社常见中译本） · status:registered",
      "url": "../sources/ba-xin-xian-gei-hai-zi-zh.md"
    },
    {
      "slug": "each-one-must-shine",
      "title": "Each One Must Shine: The Educational Legacy of V. A. Sukhomlinsky",
      "lang": "EN",
      "meta": "Peter Lang (2009, 2nd ed.) · 2009 · status:registered",
      "url": "https://archive.org/details/EachOneMustShine-EducationalLegacyOfV.A.Sukhomlinsky"
    },
    {
      "slug": "gei-jiao-shi-de-jian-yi-zh",
      "title": "给教师的建议",
      "lang": "ZH",
      "meta": "教育科学出版社 · status:registered",
      "url": "../sources/gei-jiao-shi-de-jian-yi-zh.md"
    },
    {
      "slug": "jiao-yu-zhen-yan-zh",
      "title": "苏霍姆林斯基教育箴言",
      "lang": "ZH",
      "meta": "（待核对，疑为教育科学出版社） · status:registered",
      "url": "../sources/jiao-yu-zhen-yan-zh.md"
    },
    {
      "slug": "on-education",
      "title": "On Education",
      "lang": "EN",
      "meta": "Progress Publishers · 1977 · status:registered",
      "url": "https://archive.org/details/vasili-sukhomlinsky-on-education-progress-1977"
    },
    {
      "slug": "to-children-i-give-my-heart",
      "title": "To Children I Give My Heart",
      "lang": "EN",
      "meta": "Progress Publishers · status:registered",
      "url": "https://archive.org/details/ToChildrenIGiveMyHeart-English-VasilySukhomlinsky"
    },
    {
      "slug": "xuan-ji-zh-vol1",
      "title": "苏霍姆林斯基选集（五卷本）第1卷",
      "lang": "ZH",
      "meta": "教育科学出版社（据首页 OCR） · status:registered",
      "url": "../sources/xuan-ji-zh-vol1.md"
    },
    {
      "slug": "xuan-ji-zh-vol2",
      "title": "苏霍姆林斯基选集（五卷本）第2卷",
      "lang": "ZH",
      "meta": "教育科学出版社（据首页 OCR） · status:registered",
      "url": "../sources/xuan-ji-zh-vol2.md"
    },
    {
      "slug": "xuan-ji-zh-vol3",
      "title": "苏霍姆林斯基选集（五卷本）第3卷",
      "lang": "ZH",
      "meta": "教育科学出版社（据首页 OCR） · status:registered",
      "url": "../sources/xuan-ji-zh-vol3.md"
    },
    {
      "slug": "xuan-ji-zh-vol4",
      "title": "苏霍姆林斯基选集（五卷本）第4卷",
      "lang": "ZH",
      "meta": "教育科学出版社（据首页 OCR） · status:registered",
      "url": "../sources/xuan-ji-zh-vol4.md"
    },
    {
      "slug": "xuan-ji-zh-vol5",
      "title": "苏霍姆林斯基选集（五卷本）第5卷",
      "lang": "ZH",
      "meta": "教育科学出版社（据首页 OCR） · status:registered",
      "url": "../sources/xuan-ji-zh-vol5.md"
    }
  ],
  "topics": [
    {
      "slug": "family-school",
      "title": "家校合作",
      "aliases": "家长学校 · 家校共育 · 家庭教育",
      "summary": "苏霍姆林斯基把家庭视为教育系统中不可替代的一环：父母是孩子的第一任老师，学校必须与家庭同向同行，必要时承担补偿性关怀。",
      "core": [
        "孩子是父母道德生活的一面镜子；父母日常的善良与对他人的关心，会“毫不费力”地成为孩子的道德底色（参见 sk-0009）。",
        "学校与家长的任务一致：让每个孩子感到幸福；教师只有与父母一同努力才能做到（参见 sk-0010）。",
        "学校不能完全取代家庭，尤其不能替代母亲/亲情；但若孩子在家缺少温暖，教师必须格外留心并补偿（参见 sk-0013）。",
        "学业落后与健康问题往往需要家庭、学校、医生三方合力（参见 sk-0012）。"
      ],
      "methods": [
        "**入学前就开始“家长学校”**：面向 2–6 岁儿童家长，系统教授身体、心理、智力、道德、审美发展与“如何教孩子思考”（参见 sk-0011）。",
        "**把家校关系从“孩子出问题再找家长”提前为“共同培养人”**：先对齐幸福与成人的目标，再谈具体方法（参见 sk-0010）。",
        "**个案协同**：学业落后时把家长、医生、教师放在同一张桌子上排查健康因素（参见 sk-0012）。",
        "**对家庭功能缺失的孩子主动补偿**：学校不能替代家庭，但教师应对缺少温暖的孩子更细心、更关注（参见 sk-0013）。"
      ],
      "cross": "- 中文《把心献给孩子》提供了家庭镜像、家长学校、家校医协同等直接材料（sk-0009~sk-0012）。"
    },
    {
      "slug": "learning-difficulties",
      "title": "学习困难学生",
      "aliases": "后进生 · 学业落后 · slow learners",
      "summary": "苏霍姆林斯基如何理解与帮助学习困难学生：不归因于孩子“笨”，而从健康、教育路径、思维训练与长期个别化工作入手。",
      "core": [
        "后进生在普通学校中应被接纳和帮助，而不是被隔离或贴上“低能”标签；他们不是丑陋者，而是人类花园里最娇嫩的花（参见 sk-0001）。",
        "教师面对难教孩子感到无力，往往不是因为孩子无药可救，而是教育路径错了——只纠错、不发展积极潜能（参见 sk-0003）。",
        "大量学业失败背后有健康、作息与家庭协同问题，需要先排查（参见 sk-0005）。"
      ],
      "methods": [
        "**先做健康与生活排查**：把“学业落后”当作可能需要母亲、父亲、医生、教师共同解决的问题（参见 sk-0005）。",
        "**先恢复“可教性”再谈要求**：不吼叫、不说教、不急着惩罚；先让孩子处于能听进教师话语的状态，并给额外帮助（参见 sk-0002）。",
        "**从积极潜能入手**：从孩子入学第一天起就发现并巩固他的优势，而不是只盯着缺陷“除草”（参见 sk-0003）。",
        "**保护尊严，不羞辱**：不把孩子说成“笨/没救”，避免让他在集体中感到自己是劣等者（参见 sk-0001）。",
        "**进行具体的思维训练**：对思维链容易断的孩子，可用民间谜题/多步任务训练“在头脑中记住 2–4 步”，而不是无限加码背诵（参见 sk-0007、sk-0008）。",
        "**系统投入并记录长期进步**：像苏霍姆林斯基两年把低识字率减半那样，把问题当具体战役来打；同时接受不同孩子的进步节奏不同（参见 sk-0004、sk-0006）。"
      ],
      "cross": "- **On Education** 提供了理论立场与方法原则：不隔离、不羞辱、先可教、找积极面、查健康、做长期投入（sk-0001~sk-0005）。"
    }
  ],
  "cards": [
    {
      "id": "sk-0001",
      "type": "quote",
      "title": "后进生是花园里最娇嫩的花",
      "source": "on-education",
      "topics": [
        "learning-difficulties"
      ],
      "excerpt": "Such children should be taught in ordinary schools; it would be quite out of the question to set up for them any special educational establishments, that would be contrary to elementary humanity. These children are not ugly, merely the frailest and most delicate of all the flowers in mankind's infinitely various garden. It is not their fault that they came into our schools thin, weak and defenceless.",
      "cn": "苏霍姆林斯基反对把学习困难儿童从普通学校中“隔离”出去，认为专门设校反而违背基本人道。他说这些孩子并不丑陋，只是人类花园里最娇嫩脆弱的花；他们的薄弱不是自己的过错。",
      "ref": "On Education (Progress Publishers, 1977), Foreword by S. Soloveichik, p. 22（EPUB page 23）"
    },
    {
      "id": "sk-0002",
      "type": "method",
      "title": "先让孩子变得“可教”，而不是吼叫与说教",
      "source": "on-education",
      "topics": [
        "learning-difficulties"
      ],
      "excerpt": "Children never respond to angry words... Before a child can be educated he has to be rendered educable. Before the teacher addresses himself directly to a child, it is essential that the child should be in a state in which he is capable of taking in the teacher's words... Just as he should refrain from shouting at weak pupils and give them additional help instead, so he should stop himself shouting at pupils who do not pay attention.",
      "cn": "面对“说不动”的孩子，教师常以为问题是孩子不听话；苏霍姆林斯基认为真正要做的是先恢复孩子的“可教育性”——让儿童处于能听进教师话语的状态。对弱生不吼叫，而是给额外帮助；对道德引导也同样，不用惩罚和向家长告状开路。",
      "ref": "On Education (Progress Publishers, 1977), p. 34（EPUB page 35）"
    },
    {
      "id": "sk-0003",
      "type": "principle",
      "title": "教育失灵不是孩子不可救药，而是路径错了",
      "source": "on-education",
      "topics": [
        "learning-difficulties"
      ],
      "excerpt": "The reason for a teacher's helplessness when faced by a difficult pupil... does not lie in the fact that the pupil is beyond improvement, but that the actual education process is not proceeding along the right path: the educator is endeavouring only to root out defects or better still to forestall their appearance... From the day he arrives at school it is vital to perceive and tirelessly to consolidate and develop a child's positive potential.",
      "cn": "教师面对“难教的孩子”感到无能为力，通常不是因为孩子真的不可救药，而是教育路径错了——只想着“纠错”或“防错”。苏霍姆林斯基主张从孩子入学第一天起就发现并持续巩固、发展他的积极潜能，而不是整天盯着缺陷。",
      "ref": "On Education (Progress Publishers, 1977), p. 72（EPUB page 73）"
    },
    {
      "id": "sk-0004",
      "type": "case",
      "title": "两年把低识字率减半的第一次“战役”",
      "source": "on-education",
      "topics": [
        "learning-difficulties"
      ],
      "excerpt": "When Sukhomlinsky began his teaching career, his first concern was his pupil's literacy. Many children used to have to repeat years because of their weak written work... Two years' intensive work enabled Sukhomlinsky to cut down the numbers with a low literacy rating by half. That was the first major achievement in the school's history—the first battle and the first victory.",
      "cn": "苏霍姆林斯基从教初期面对的“老大难”是大量学生因书写/读写弱而留级。他没有把问题归为孩子笨，而是投入两年密集工作，把低识字率学生数量降低一半。他把这称为学校历史上“第一次战斗与第一次胜利”。",
      "ref": "On Education (Progress Publishers, 1977), Foreword by S. Soloveichik, p. 25（EPUB page 26）"
    },
    {
      "id": "sk-0005",
      "type": "principle",
      "title": "85% 学业失败的首要原因是健康",
      "source": "on-education",
      "topics": [
        "learning-difficulties"
      ],
      "excerpt": "Experience has shown us that in 85 per cent of cases where children are doing badly at school, the main reason for backwardness is poor health, some indisposition or illness, more often than not of a quite imperceptible variety but something that can only be put to right, provided there is concerted effort on the part of mother, father, doctor and teacher.",
      "cn": "苏霍姆林斯基根据长期观察提出：约 85% 的学业落后首要原因不是智力，而是健康——往往是家长和教师不易察觉的轻微不适或疾病。要解决它，需要母亲、父亲、医生和教师协同努力。",
      "ref": "On Education (Progress Publishers, 1977), p. 114（EPUB page 115）"
    },
    {
      "id": "sk-0006",
      "type": "case",
      "title": "瓦尔娅、彼得里克与谜题：慢学习者的六个月",
      "source": "to-children-i-give-my-heart",
      "topics": [
        "learning-difficulties"
      ],
      "excerpt": "I started to work separately with my slow learners... These riddles were an irreplaceable means of training the mind. The children had to remember from two to four \"moves\" to solve each of them. In six months, Valya and Slava could solve such problems, but Petrik and Nina still had no luck... I studied the thinking of children, especially such slow learners as Valya, Petrik, and Nina, not for some kind of theoretical goals, but to facilitate their intellectual labor—to teach them to study.",
      "cn": "苏霍姆林斯基在“快乐学校”阶段观察到 Valya、Nina、Petrik、Slava 等孩子在解谜题时“思维链中断”。他开始与慢学习者单独工作，用民间谜题训练他们“在心中记住 2–4 步”。六个月后 Valya 和 Slava 能解出这类题，Petrik 和 Nina 仍困难——他并不因此放弃，而是继续研究他们的思维特点，目的是教会他们“学习”。",
      "ref": "To Children I Give My Heart, Part “The Years of Childhood”, pp. 82–83"
    },
    {
      "id": "sk-0007",
      "type": "quote",
      "title": "思维必须被教会，否则孩子只会死记硬背",
      "source": "to-children-i-give-my-heart",
      "topics": [
        "learning-difficulties"
      ],
      "excerpt": "The ability to think must be taught, or otherwise the children will strain their memories and cram, dulling their thoughts even more.",
      "cn": "慢学习者的问题常常被误判为“记不住”；苏霍姆林斯基认为真正的解法是教他们“想”——如果只逼记忆和背诵，孩子的思维会更钝。思维本身是需要教学的能力。",
      "ref": "To Children I Give My Heart, Part “The Years of Childhood”, p. 83"
    },
    {
      "id": "sk-0008",
      "type": "practice",
      "title": "用民间谜题单独训练“思维步数”",
      "source": "to-children-i-give-my-heart",
      "topics": [
        "learning-difficulties"
      ],
      "excerpt": "I started to work separately with my slow learners. I gave them simple folk riddles designed to deepen comprehension of natural numbers and to determine the interdependence of numbers... The children had to remember from two to four \"moves\" to solve each of them.",
      "cn": "实践要点：",
      "ref": "To Children I Give My Heart, Part “The Years of Childhood”, pp. 82–83"
    },
    {
      "id": "sk-0009",
      "type": "quote",
      "title": "孩子是父母道德生活的一面镜子",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "family-school"
      ],
      "excerpt": "孩子是父母道德生活的一面镜子。我曾思考过每个家庭的利和弊。好父母最有价值且毫不费力就能灌输给子女的道德品质是父母内心的善良和善待他人的能力。",
      "cn": "孩子不是靠听父母“讲道理”长大的，而是通过观察父母如何对待他人、如何生活形成最初的道德面貌。父母内心真正的善良会“毫不费力”地传递给孩子；反之，利己主义与盲目溺爱也会成为祸根。",
      "ref": "把心献给孩子（中文），《我的学生家长》"
    },
    {
      "id": "sk-0010",
      "type": "principle",
      "title": "教师只有与父母一同努力，才能带给孩子巨大幸福",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "family-school"
      ],
      "excerpt": "孩子是家庭的一面镜子。正如水滴里能映出太阳一样，父母的道德节操也会反映在孩子们的身上。因此，学校和家长们的任务是要让每一个孩子都感到幸福……教师只有与父母一同努力，才能带给孩子们巨大的幸福。",
      "cn": "学校与家庭不是“交接孩子的两端”，而是共同承担同一任务：让每个孩子感到幸福。幸福不是单靠学校或单靠家庭能完成的，教师必须与父母形成合力。",
      "ref": "把心献给孩子（中文），《我的学生家长》"
    },
    {
      "id": "sk-0011",
      "type": "practice",
      "title": "家长培训班：在孩子入学前就培训家长",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "family-school"
      ],
      "excerpt": "为了关注学龄前儿童的状况，我们成立了家长培训班，请2～6岁大儿童的家长来学习……我们力求让家长学到一定的知识和技能。家长培训学校的课程特别关注这样一个问题，就是如何教孩子思考、通过什么途径提高孩子的智力……我们还与家长们一起制订了一个关于学龄前儿童走进大自然的计划……我们还非常注重，让每一个有学龄前儿童的家庭能够营造出浓厚的读书氛围。",
      "cn": "帕夫雷什中学的“家长学校/家长培训班”在孩子入学前就已开始，面向 2–6 岁儿童的家长。内容覆盖身体、心理、智力、道德、审美发展，特别教家长如何应对孩子的提问、如何带孩子走进自然、如何营造家庭读书氛围。",
      "ref": "把心献给孩子（中文），《生活习题集里的一千道题》"
    },
    {
      "id": "sk-0012",
      "type": "principle",
      "title": "85% 学业落后与健康有关，需要家校医合力",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "family-school",
        "learning-difficulties"
      ],
      "excerpt": "经验告诉我们，大约85%成绩不及格的学生之所以学业落后，主要是因为身体状况不佳，身体有某种不适或疾病。而这些身体异常往往完全不被察觉，因此只有在父母、医生和老师的共同努力下，才能治愈这些疾病。",
      "cn": "这是“85% 学业失败与健康有关”论断的中文版本，与 On Education 中的英文表述相互印证。它说明：当孩子成绩落后时，学校不能只从教学找原因，需要父母、医生、教师三方协同排查健康。",
      "ref": "把心献给孩子（中文），《大自然是健康之源》"
    },
    {
      "id": "sk-0013",
      "type": "quote",
      "title": "学校不能完全取代家庭，教师要对缺失温暖的孩子格外留心",
      "source": "on-education",
      "topics": [
        "family-school"
      ],
      "excerpt": "School cannot fully take the place of the family, in particular a child's mother, but if a child is deprived of kind concern, warmth and care at home, we teachers must be particularly attentive to his needs.",
      "cn": "苏霍姆林斯基承认学校无法完全替代家庭，尤其是母亲的角色；正因如此，当孩子在家中缺少温暖与关怀时，教师更要格外关注他的需要。",
      "ref": "On Education (Progress Publishers, 1977), EPUB page 67（The Need to Understand the Workings of the Child's Heart）"
    }
  ]
};
