/* AUTO-GENERATED by scripts/build_site.py — do not edit manually. */
window.KB_DATA = {
  "sources": [
    {
      "slug": "ba-xin-xian-gei-hai-zi-zh",
      "title": "把心献给孩子",
      "lang": "ZH",
      "meta": "未知（电子版，对应教育科学出版社常见中译本） · status:registered",
      "url": "../sources/ba-xin-xian-gei-hai-zi-zh.md"
    },
    {
      "slug": "each-one-must-shine",
      "title": "Each One Must Shine: The Educational Legacy of V. A. Sukhomlinsky",
      "lang": "EN",
      "meta": "Peter Lang (2009, 2nd ed.) · 2009 · status:complete",
      "url": "https://archive.org/details/EachOneMustShine-EducationalLegacyOfV.A.Sukhomlinsky"
    },
    {
      "slug": "gei-jiao-shi-de-jian-yi-zh",
      "title": "给教师的建议",
      "lang": "ZH",
      "meta": "教育科学出版社 · status:registered",
      "url": "../sources/gei-jiao-shi-de-jian-yi-zh.md"
    },
    {
      "slug": "jiao-yu-zhen-yan-zh",
      "title": "苏霍姆林斯基教育箴言",
      "lang": "ZH",
      "meta": "教育科学出版社 · 2016 · status:complete",
      "url": "../sources/jiao-yu-zhen-yan-zh.md"
    },
    {
      "slug": "on-education",
      "title": "On Education",
      "lang": "EN",
      "meta": "Progress Publishers · 1977 · status:registered",
      "url": "https://archive.org/details/vasili-sukhomlinsky-on-education-progress-1977"
    },
    {
      "slug": "to-children-i-give-my-heart",
      "title": "To Children I Give My Heart",
      "lang": "EN",
      "meta": "Progress Publishers · status:registered",
      "url": "https://archive.org/details/ToChildrenIGiveMyHeart-English-VasilySukhomlinsky"
    },
    {
      "slug": "xuan-ji-zh-vol1",
      "title": "苏霍姆林斯基选集（五卷本）第1卷",
      "lang": "ZH",
      "meta": "教育科学出版社（据首页 OCR） · status:registered",
      "url": "../sources/xuan-ji-zh-vol1.md"
    },
    {
      "slug": "xuan-ji-zh-vol2",
      "title": "苏霍姆林斯基选集（五卷本）第2卷",
      "lang": "ZH",
      "meta": "教育科学出版社（据首页 OCR） · status:registered",
      "url": "../sources/xuan-ji-zh-vol2.md"
    },
    {
      "slug": "xuan-ji-zh-vol3",
      "title": "苏霍姆林斯基选集（五卷本）第3卷",
      "lang": "ZH",
      "meta": "教育科学出版社（据首页 OCR） · status:registered",
      "url": "../sources/xuan-ji-zh-vol3.md"
    },
    {
      "slug": "xuan-ji-zh-vol4",
      "title": "苏霍姆林斯基选集（五卷本）第4卷",
      "lang": "ZH",
      "meta": "教育科学出版社（据首页 OCR） · status:registered",
      "url": "../sources/xuan-ji-zh-vol4.md"
    },
    {
      "slug": "xuan-ji-zh-vol5",
      "title": "苏霍姆林斯基选集（五卷本）第5卷",
      "lang": "ZH",
      "meta": "教育科学出版社（据首页 OCR） · status:registered",
      "url": "../sources/xuan-ji-zh-vol5.md"
    }
  ],
  "topics": [
    {
      "slug": "aesthetic-nature-education",
      "title": "美育与自然",
      "aliases": "美育 · 自然教育 · 审美教育",
      "summary": "苏霍姆林斯基认为自然与艺术中的美能提升儿童心灵的敏感性，是道德教育的重要入口；美育需要耐心等待个体觉醒，并最终转化为保护美、创造美的行动。",
      "core": [
        "自然、书籍与人中的美能使儿童心灵变得高尚，增强对道德影响的敏感性（参见 sk-0024）。",
        "美的觉醒不能被“讲解”催熟，教师需要长期提供接触美的机会并耐心等待（参见 sk-0025）。",
        "儿童对世界的审美有自己独特的“童话语言”，教育应保护它，而不是用成人标准去翻译/纠正（参见 sk-0027）。",
        "欣赏美只是善良情感的萌芽，必须发展为保护美、创造美的行动（参见 sk-0028）。"
      ],
      "methods": [
        "**让儿童在真实自然中选择美**：带孩子到草地/田野，让他自己决定“画什么/看什么”，而不是给定统一对象（参见 sk-0026）。",
        "**把美育纳入课程结构**：用“非实用”的文学、音乐、绘画、自然观察平衡过度实用的教育（参见 sk-0024）。",
        "**降低即时反馈期待**：不要求孩子“当堂感动”，持续提供美的经验，等待个体内在觉醒（参见 sk-0025）。",
        "**保护儿童的想象语言**：技法（比例/透视等）可以教，但不要用成人标准破坏孩子的童话式表达（参见 sk-0027）。",
        "**让审美转化为行动**：把“欣赏美”延伸为种花、护树、为他人创造美等具体行为（参见 sk-0028）。"
      ],
      "cross": "- On Education 提供美育的原理：美提升心灵敏感性、美的唤醒需要耐心、教育不能只重实用（sk-0024、sk-0025）。"
    },
    {
      "slug": "assessment-grading",
      "title": "评价与分数",
      "aliases": "评分 · 成绩 · 考试评价",
      "summary": "苏霍姆林斯基认为分数是精细的教育工具：只应肯定积极成果，不能用来惩罚或告状；评价需要信任、分寸，避免公开比较与羞辱。",
      "core": [
        "评分只应反映积极的脑力劳动成果，不应作为惩罚手段（参见 sk-0044）。",
        "不能拿不及格去“让家长惩罚孩子”，这会让孩子把学校、家长和脑力劳动一起对立起来（参见 sk-0045）。",
        "分数与监督不应建立在“不信任”之上；连“家长签名”都可能破坏教育基础（参见 sk-0046）。",
        "不公平的低分是撒谎、隐瞒与懒惰的温床（参见 sk-0047）。",
        "评价能力不同的学生需要分寸感，避免“谁好谁差”的公开比较（参见 sk-0048）。"
      ],
      "methods": [
        "**只给积极成果评分**：暂时没掌握就先不给分，继续帮助，而不是用低分标记失败（参见 sk-0044）。",
        "**禁止“借家长之手惩罚”**：低分必须伴随帮助方案，而不是告状信号（参见 sk-0045）。",
        "**减少监督式签名/告状式反馈**：用信任与自我负责替代互相防范（参见 sk-0046）。",
        "**处理撒谎时先反思机制**：不公平低分与不信任才是欺骗的土壤（参见 sk-0047）。",
        "**用个人化反馈替代公开比较**：不说“谁好谁差”，说“你这次进步/这一部分掌握了”（参见 sk-0048）。"
      ],
      "cross": "- 中文《把心献给孩子》集中呈现苏霍姆林斯基的评分伦理：只评积极成果、不用分数告状、不靠签名监督、用信任代替防范（sk-0044~sk-0047）。"
    },
    {
      "slug": "child-study",
      "title": "儿童研究",
      "aliases": "研究儿童 · 了解儿童 · 儿童观察",
      "summary": "苏霍姆林斯基把“研究儿童”视为教育的前提：了解家庭、追溯早期环境、进入儿童内心世界，才能在公平与个别化基础上展开真正教育。",
      "core": [
        "要了解孩子，就要清楚了解他的家庭（参见 sk-0049）。",
        "帕夫雷什在开学前就逐户熟悉每个家庭，识别谁缺少幸福与尊重（参见 sk-0050）。",
        "很多后进生是一本“紧闭的书”，不进入其内心世界就无法谈敏感与教育（参见 sk-0051）。",
        "真正的公平来自对每个儿童内心世界的深入了解，而不是抽象规则（参见 sk-0052）。",
        "学龄前缺少照看与信息会熄灭好奇心；教育干预需要追溯早期经验（参见 sk-0053）。"
      ],
      "methods": [
        "**建立“家庭背景”视角**：了解学生的家庭结构、亲子关系与养育方式（参见 sk-0049）。",
        "**入学前做家访/家庭访谈**：提前识别缺少温暖、尊重或稳定照看的孩子（参见 sk-0050）。",
        "**把后进生当“需要读懂的书”**：先研究其思维特点与内心世界，再谈教学与帮助（参见 sk-0051）。",
        "**用个案理解支撑公平**：处理公平争议时，先问自己是否真正了解每个孩子的处境（参见 sk-0052）。",
        "**追溯早期经验**：对冷漠/无兴趣学生，了解其学龄前照看与信息环境，设计补偿性干预（参见 sk-0053）。"
      ],
      "cross": "- 中文《把心献给孩子》提供“了解家庭、逐户家访、追溯早期环境”的实践路径（sk-0049、sk-0050、sk-0053）。"
    },
    {
      "slug": "collective-education",
      "title": "集体教育",
      "aliases": "班集体 · 集体建设 · 平行影响",
      "summary": "苏霍姆林斯基认为真正的集体不是压制个性的工具，而是支持每个孩子提升自尊、发展才能的土壤；集体通过真诚关怀与共同劳动发挥教育力量。",
      "core": [
        "真正的集体教育不压制个性，反而让每个孩子发展全部才能（参见 sk-0029）。",
        "集体只有当它有助于个人提升、让每个人树立自尊与自爱时，才成为教育力量（参见 sk-0030、sk-0033）。",
        "集体关怀要落实为具体传统：给没庆祝过生日的孩子过生日、探望生病伙伴等（参见 sk-0031）。",
        "对冷漠/难教的孩子，集体可作为“匹配一个热忱教师或同伴”的个别化手段（参见 sk-0032）。"
      ],
      "methods": [
        "**以“个体提升”检验集体设计**：评比、活动、班规都应让每个孩子更自尊、更愿做好人（参见 sk-0030、sk-0033）。",
        "**建立关怀型集体传统**：集体生日、探望生病同学、记住每个成员的喜好（参见 sk-0031）。",
        "**用共同劳动/共同目标联结**：集体不只是开会和规则，而是一起做真实的事（参见 sk-0032，并与“劳动教育”交叉）。",
        "**把个别化放进集体**：为冷漠的孩子在集体中寻找合适的大朋友/同伴，用关系带动转变（参见 sk-0032）。"
      ],
      "cross": "- On Education 从理论上回应“集体 vs 个性”之争：二者不矛盾，集体是个性发展的条件（sk-0029），并提供“在集体中为困难孩子匹配大朋友”的方法（sk-0032）。"
    },
    {
      "slug": "family-school",
      "title": "家校合作",
      "aliases": "家长学校 · 家校共育 · 家庭教育",
      "summary": "苏霍姆林斯基把家庭视为教育系统中不可替代的一环：父母是孩子的第一任老师，学校必须与家庭同向同行，必要时承担补偿性关怀。",
      "core": [
        "孩子是父母道德生活的一面镜子；父母日常的善良与对他人的关心，会“毫不费力”地成为孩子的道德底色（参见 sk-0009）。",
        "学校与家长的任务一致：让每个孩子感到幸福；教师只有与父母一同努力才能做到（参见 sk-0010）。",
        "学校不能完全取代家庭，尤其不能替代母亲/亲情；但若孩子在家缺少温暖，教师必须格外留心并补偿（参见 sk-0013）。",
        "学业落后与健康问题往往需要家庭、学校、医生三方合力（参见 sk-0012）。"
      ],
      "methods": [
        "**入学前就开始“家长学校”**：面向 2–6 岁儿童家长，系统教授身体、心理、智力、道德、审美发展与“如何教孩子思考”（参见 sk-0011）。",
        "**把家校关系从“孩子出问题再找家长”提前为“共同培养人”**：先对齐幸福与成人的目标，再谈具体方法（参见 sk-0010）。",
        "**个案协同**：学业落后时把家长、医生、教师放在同一张桌子上排查健康因素（参见 sk-0012）。",
        "**对家庭功能缺失的孩子主动补偿**：学校不能替代家庭，但教师应对缺少温暖的孩子更细心、更关注（参见 sk-0013）。"
      ],
      "cross": "- 中文《把心献给孩子》提供了家庭镜像、家长学校、家校医协同等直接材料（sk-0009~sk-0012）。"
    },
    {
      "slug": "health-first",
      "title": "健康第一",
      "aliases": "健康 · 户外活动 · 作息",
      "summary": "苏霍姆林斯基把健康放在教育首位：没有健康就没有正常的精神生活、智力发展与自信；健康需要学校与家庭共同落实户外、作息、饮食与锻炼。",
      "core": [
        "健康管理需要学校与家庭形成共同约定：户外、早睡、开窗、饮食、锻炼（参见 sk-0020、sk-0021）。",
        "长期户外与规律作息能带来可观察的健康改善（参见 sk-0022）。",
        "睡眠与作业安排直接影响学业：睡前长时间写作业、挤占户外时间，会让孩子开始落后（参见 sk-0023）。"
      ],
      "methods": [
        "**把健康放在时间表第一位**：先保障睡眠、户外、早餐，再谈学习时长（参见 sk-0019、sk-0020）。",
        "**与家庭签订可执行的健康约定**：固定就寝、开窗通风、每天户外、设置院子/阳台阅读休息角（参见 sk-0020）。",
        "**增加富含新鲜空气的户外活动**：田野、公园、绿植环境，卧室窗外可种绿植（参见 sk-0021）。",
        "**避免“用学习时间挤占健康”**：不让孩子睡前长时间写作业，把学习任务前移，保留游戏和户外（参见 sk-0023）。",
        "**循序渐进增强体质**：长期规律锻炼、适应自然温度、不过度保护（参见 sk-0022）。"
      ],
      "cross": "- 中文《把心献给孩子》“健康，健康，还是健康”给出了健康优先原则、家庭约定和班级实践结果（sk-0019、sk-0020、sk-0022）。"
    },
    {
      "slug": "labor-education",
      "title": "劳动教育",
      "aliases": "劳动育人 · 创造性劳动",
      "summary": "苏霍姆林斯基认为劳动不是惩罚或额外负担，而是培养品格、智力和“真正的人”的必经之路：劳动要系统完整、真实可感，并让他人因自己的劳动而快乐。",
      "core": [
        "劳动像食物一样必不可少，必须规律、系统，并让孩子完整经历从目标到成果的过程（参见 sk-0014）。",
        "劳动的意义不在于“忙起来”，而在于孩子通过劳动为他人创造价值并感到快乐；这样的孩子不会变成冷酷自私的人（参见 sk-0016、sk-0017）。",
        "劳动可以成为转化“最难教/最懒散”孩子的入口：牵着孩子一起劳动，或先体力后脑力逐步引导（参见 sk-0015、sk-0018）。"
      ],
      "methods": [
        "**选择完整的真实任务**：不要只给零散杂务，选一件需要持续数周/数月、有明确成果的任务，让孩子走完目标→努力→成果→庆祝（参见 sk-0014、sk-0016）。",
        "**让劳动有“为他人的快乐”**：例如为母亲种果树、为集体种花、把收成送给父母——赋予劳动道德与情感意义（参见 sk-0016、sk-0017）。",
        "**对难教的孩子，从共同劳动开始**：不先讲道理，而是“牵着手一起到葡萄园干活”，在共同目标中建立关系（参见 sk-0015）。",
        "**用体力劳动作为脑力兴趣的入口**：对最懒散、被忽视的学生，先让他完成可胜任的体力工作，再引导他看到其中的知识与创造（参见 sk-0018）。"
      ],
      "cross": "- On Education 提供劳动教育的原则与方法：系统完整、集体共同劳动、体力与脑力结合（sk-0014、sk-0015、sk-0018）。"
    },
    {
      "slug": "learning-difficulties",
      "title": "学习困难学生",
      "aliases": "后进生 · 学业落后 · slow learners",
      "summary": "苏霍姆林斯基如何理解与帮助学习困难学生：不归因于孩子“笨”，而从健康、教育路径、思维训练与长期个别化工作入手。",
      "core": [
        "后进生在普通学校中应被接纳和帮助，而不是被隔离或贴上“低能”标签；他们不是丑陋者，而是人类花园里最娇嫩的花（参见 sk-0001）。",
        "教师面对难教孩子感到无力，往往不是因为孩子无药可救，而是教育路径错了——只纠错、不发展积极潜能（参见 sk-0003）。",
        "大量学业失败背后有健康、作息与家庭协同问题，需要先排查（参见 sk-0005）。"
      ],
      "methods": [
        "**先做健康与生活排查**：把“学业落后”当作可能需要母亲、父亲、医生、教师共同解决的问题（参见 sk-0005）。",
        "**先恢复“可教性”再谈要求**：不吼叫、不说教、不急着惩罚；先让孩子处于能听进教师话语的状态，并给额外帮助（参见 sk-0002）。",
        "**从积极潜能入手**：从孩子入学第一天起就发现并巩固他的优势，而不是只盯着缺陷“除草”（参见 sk-0003）。",
        "**保护尊严，不羞辱**：不把孩子说成“笨/没救”，避免让他在集体中感到自己是劣等者（参见 sk-0001）。",
        "**进行具体的思维训练**：对思维链容易断的孩子，可用民间谜题/多步任务训练“在头脑中记住 2–4 步”，而不是无限加码背诵（参见 sk-0007、sk-0008）。",
        "**系统投入并记录长期进步**：像苏霍姆林斯基两年把低识字率减半那样，把问题当具体战役来打；同时接受不同孩子的进步节奏不同（参见 sk-0004、sk-0006）。"
      ],
      "cross": "- **On Education** 提供了理论立场与方法原则：不隔离、不羞辱、先可教、找积极面、查健康、做长期投入（sk-0001~sk-0005）。"
    },
    {
      "slug": "love-education",
      "title": "爱的教育",
      "aliases": "教育爱 · 把心献给孩子",
      "summary": "苏霍姆林斯基把“爱孩子”视为教育的起点，但不是情感泛滥或溺爱，而是厚爱与明智严厉结合、让孩子获得真实幸福与自信、对缺少疼爱的孩子加倍关心的实践。",
      "core": [
        "真正的儿童教育者必须把自己的心交给孩子（参见 sk-0039）。",
        "教育爱不是溺爱，而是让孩子通过努力获得幸福、自信与成功体验（参见 sk-0040）。",
        "教育爱是厚爱与明智严厉、父母般严格要求的结合（参见 sk-0041）。",
        "爱要体现在细节中：察觉孩子不对劲时不公开追问，先传递“我看见了”，再私下交谈（参见 sk-0042）。",
        "对家庭中缺少疼爱的孩子，教师更要倍加关心（参见 sk-0043）。"
      ],
      "methods": [
        "**以“真实幸福”检验爱**：不包办、不代劳，让孩子在努力与成功中体验自信（参见 sk-0040）。",
        "**温暖与要求并行**：爱包含理解和尊重，也包含明智严厉与合理期待（参见 sk-0041）。",
        "**练习“看见但不打扰”的关怀**：从眼神/状态发现异常，不当众追问，创造私下安全沟通时机（参见 sk-0042）。",
        "**对缺爱的孩子主动补偿**：不替代家庭，但格外稳定地给予关心与关注（参见 sk-0043）。",
        "**把“献出心”作为职业起点**：教师自我反思是否真正愿意进入孩子的世界（参见 sk-0039）。"
      ],
      "cross": "- 中文《把心献给孩子》从书名到内容都体现“献出心”的主题，并提供“厚爱+严格要求”“补偿缺爱孩子”等表述（sk-0039、sk-0041、sk-0043）。"
    },
    {
      "slug": "reading-and-books",
      "title": "阅读与书籍",
      "aliases": "阅读教育 · 班级图书 · 读书",
      "summary": "苏霍姆林斯基把阅读视为精神生活与自我教育的起点：真正的阅读是对语言美的敏感，需要成人大声朗读、精选少量好书并允许反复深读。",
      "core": [
        "真正的阅读是对词句含义、美感与细微差别保持敏感，而不是只求流利（参见 sk-0054）。",
        "孩子第一次阅读前，应先听成人大声朗读，感受语言与艺术形象之美（参见 sk-0055）。",
        "阅读环境应“少而精”：班级藏书库、反复阅读喜爱作品，比贪多更重要（参见 sk-0056）。",
        "自我教育与精神独立从读书开始；教师最终要放手让学生走向书的世界（参见 sk-0057）。",
        "帕夫雷什的“思考室”只放 300 本世界杰作，鼓励反复深读（参见 sk-0058）。"
      ],
      "methods": [
        "**从“朗读输入”开始**：在孩子独立阅读前，由老师/父母大声朗读，用听觉建立语感（参见 sk-0055）。",
        "**培养对语言美的敏感**：不只问“讲了什么”，还让孩子体会词句的形象、声音与情感（参见 sk-0054）。",
        "**建小而精的班级藏书库**：精选少量高质量图书，鼓励集体朗读和反复阅读（参见 sk-0056）。",
        "**设置经典反复读空间**：类似“思考室/经典阅读角”，用少数杰作培养深度阅读（参见 sk-0058）。",
        "**把阅读引向自我教育**：让书成为精神需求，逐步培养学生独立阅读、独立思考的习惯（参见 sk-0057）。"
      ],
      "cross": "- 中文《把心献给孩子》提供了完整阅读教学实践：朗读输入、词汇库、班级藏书库、反复阅读、图书节（sk-0054~sk-0057）。"
    },
    {
      "slug": "teacher-growth",
      "title": "教师成长",
      "aliases": "教师素养 · 教师专业发展 · 教育修养",
      "summary": "苏霍姆林斯基认为教师成长的核心不是技巧堆砌，而是对孩子的信念与爱、被保护的自由时间、与儿童共同生活的经历，以及在批评中仍守护孩子希望的能力。",
      "core": [
        "没有对孩子的信念就没有教育；缺少信念就是缺少爱（参见 sk-0034）。",
        "教师的自由时间是其创造力的根，学校管理不应以形式化事务耗尽教师（参见 sk-0035）。",
        "对低龄儿童，教师应像母亲一样亲近；师生信任是教育的基本规则（参见 sk-0036）。",
        "教师不只是课堂上的导师，还应是孩子生活中的朋友与同伴（参见 sk-0037）。",
        "即使批评孩子，也不能扑灭他“还有目标要追”的信念（参见 sk-0038）。"
      ],
      "methods": [
        "**把“信念/爱”纳入教师评价与培养**：不只考核成绩和课堂，还关注教师是否相信每个孩子能变好（参见 sk-0034）。",
        "**保护教师自由时间**：减少书面报表与形式化值班，用抽样批改/共同教研替代机械劳动（参见 sk-0035）。",
        "**安排师生共同生活**：远足、劳动、课外活动，让教师成为学生的朋友和同伴（参见 sk-0037）。",
        "**训练“守护希望式批评”**：批评后仍让孩子看到方向与目标，不羞辱、不判死刑（参见 sk-0038）。",
        "**重视低年级教师的“亲近力”**：把建立信任关系作为低龄教师的核心能力（参见 sk-0036）。"
      ],
      "cross": "- On Education 从学校管理与教师信念角度谈教师成长：自由时间、信念、批评边界（sk-0034、sk-0035、sk-0038）。"
    },
    {
      "slug": "thinking-and-nature",
      "title": "思维课与大自然",
      "aliases": "大自然的书 · 思维课 · 自然观察",
      "summary": "苏霍姆林斯基把大自然当作发展思维的系统课程：不是把孩子放进自然就自动变聪明，而是通过有计划观察与因果思考，让自然成为思维源泉。",
      "core": [
        "每周两次走进大自然，是为了“学习思考”，不是游玩（参见 sk-0059）。",
        "教育不能把孩子变成知识仓库；必须教他思考，而不是用记忆和背诵代替理解（参见 sk-0060）。",
        "大自然本身没有教育魔力；只有当人认识自然、思考因果关系时，它才成为教育资源（参见 sk-0061、sk-0063）。",
        "帕夫雷什用四年 300 次系统观察组成《大自然的书》，把自然观察课程化（参见 sk-0062）。"
      ],
      "methods": [
        "**把户外变成思维课**：每次自然活动设计观察主题与因果问题，而非自由游玩（参见 sk-0059）。",
        "**用思考替代死记硬背**：减少机械记忆任务，增加比较、提问、因果推理（参见 sk-0060）。",
        "**先问因果，再进自然**：进入现场前明确要观察什么现象、思考什么关系（参见 sk-0061、sk-0063）。",
        "**系统规划观察课程**：像《大自然的书》一样按年级规划 300 次左右的观察序列（参见 sk-0062）。"
      ],
      "cross": "- 中文《把心献给孩子》“三百页《大自然的书》”提供了完整实践与课程结构（sk-0059~sk-0062）。"
    }
  ],
  "cards": [
    {
      "id": "sk-0001",
      "type": "quote",
      "title": "后进生是花园里最娇嫩的花",
      "source": "on-education",
      "topics": [
        "learning-difficulties"
      ],
      "excerpt": "Such children should be taught in ordinary schools; it would be quite out of the question to set up for them any special educational establishments, that would be contrary to elementary humanity. These children are not ugly, merely the frailest and most delicate of all the flowers in mankind's infinitely various garden. It is not their fault that they came into our schools thin, weak and defenceless.",
      "cn": "苏霍姆林斯基反对把学习困难儿童从普通学校中“隔离”出去，认为专门设校反而违背基本人道。他说这些孩子并不丑陋，只是人类花园里最娇嫩脆弱的花；他们的薄弱不是自己的过错。",
      "ref": "On Education (Progress Publishers, 1977), Foreword by S. Soloveichik, p. 22（EPUB page 23）"
    },
    {
      "id": "sk-0002",
      "type": "method",
      "title": "先让孩子变得“可教”，而不是吼叫与说教",
      "source": "on-education",
      "topics": [
        "learning-difficulties"
      ],
      "excerpt": "Children never respond to angry words... Before a child can be educated he has to be rendered educable. Before the teacher addresses himself directly to a child, it is essential that the child should be in a state in which he is capable of taking in the teacher's words... Just as he should refrain from shouting at weak pupils and give them additional help instead, so he should stop himself shouting at pupils who do not pay attention.",
      "cn": "面对“说不动”的孩子，教师常以为问题是孩子不听话；苏霍姆林斯基认为真正要做的是先恢复孩子的“可教育性”——让儿童处于能听进教师话语的状态。对弱生不吼叫，而是给额外帮助；对道德引导也同样，不用惩罚和向家长告状开路。",
      "ref": "On Education (Progress Publishers, 1977), p. 34（EPUB page 35）"
    },
    {
      "id": "sk-0003",
      "type": "principle",
      "title": "教育失灵不是孩子不可救药，而是路径错了",
      "source": "on-education",
      "topics": [
        "learning-difficulties"
      ],
      "excerpt": "The reason for a teacher's helplessness when faced by a difficult pupil... does not lie in the fact that the pupil is beyond improvement, but that the actual education process is not proceeding along the right path: the educator is endeavouring only to root out defects or better still to forestall their appearance... From the day he arrives at school it is vital to perceive and tirelessly to consolidate and develop a child's positive potential.",
      "cn": "教师面对“难教的孩子”感到无能为力，通常不是因为孩子真的不可救药，而是教育路径错了——只想着“纠错”或“防错”。苏霍姆林斯基主张从孩子入学第一天起就发现并持续巩固、发展他的积极潜能，而不是整天盯着缺陷。",
      "ref": "On Education (Progress Publishers, 1977), p. 72（EPUB page 73）"
    },
    {
      "id": "sk-0004",
      "type": "case",
      "title": "两年把低识字率减半的第一次“战役”",
      "source": "on-education",
      "topics": [
        "learning-difficulties"
      ],
      "excerpt": "When Sukhomlinsky began his teaching career, his first concern was his pupil's literacy. Many children used to have to repeat years because of their weak written work... Two years' intensive work enabled Sukhomlinsky to cut down the numbers with a low literacy rating by half. That was the first major achievement in the school's history—the first battle and the first victory.",
      "cn": "苏霍姆林斯基从教初期面对的“老大难”是大量学生因书写/读写弱而留级。他没有把问题归为孩子笨，而是投入两年密集工作，把低识字率学生数量降低一半。他把这称为学校历史上“第一次战斗与第一次胜利”。",
      "ref": "On Education (Progress Publishers, 1977), Foreword by S. Soloveichik, p. 25（EPUB page 26）"
    },
    {
      "id": "sk-0005",
      "type": "principle",
      "title": "85% 学业失败的首要原因是健康",
      "source": "on-education",
      "topics": [
        "learning-difficulties"
      ],
      "excerpt": "Experience has shown us that in 85 per cent of cases where children are doing badly at school, the main reason for backwardness is poor health, some indisposition or illness, more often than not of a quite imperceptible variety but something that can only be put to right, provided there is concerted effort on the part of mother, father, doctor and teacher.",
      "cn": "苏霍姆林斯基根据长期观察提出：约 85% 的学业落后首要原因不是智力，而是健康——往往是家长和教师不易察觉的轻微不适或疾病。要解决它，需要母亲、父亲、医生和教师协同努力。",
      "ref": "On Education (Progress Publishers, 1977), p. 114（EPUB page 115）"
    },
    {
      "id": "sk-0006",
      "type": "case",
      "title": "瓦尔娅、彼得里克与谜题：慢学习者的六个月",
      "source": "to-children-i-give-my-heart",
      "topics": [
        "learning-difficulties"
      ],
      "excerpt": "I started to work separately with my slow learners... These riddles were an irreplaceable means of training the mind. The children had to remember from two to four \"moves\" to solve each of them. In six months, Valya and Slava could solve such problems, but Petrik and Nina still had no luck... I studied the thinking of children, especially such slow learners as Valya, Petrik, and Nina, not for some kind of theoretical goals, but to facilitate their intellectual labor—to teach them to study.",
      "cn": "苏霍姆林斯基在“快乐学校”阶段观察到 Valya、Nina、Petrik、Slava 等孩子在解谜题时“思维链中断”。他开始与慢学习者单独工作，用民间谜题训练他们“在心中记住 2–4 步”。六个月后 Valya 和 Slava 能解出这类题，Petrik 和 Nina 仍困难——他并不因此放弃，而是继续研究他们的思维特点，目的是教会他们“学习”。",
      "ref": "To Children I Give My Heart, Part “The Years of Childhood”, pp. 82–83"
    },
    {
      "id": "sk-0007",
      "type": "quote",
      "title": "思维必须被教会，否则孩子只会死记硬背",
      "source": "to-children-i-give-my-heart",
      "topics": [
        "learning-difficulties"
      ],
      "excerpt": "The ability to think must be taught, or otherwise the children will strain their memories and cram, dulling their thoughts even more.",
      "cn": "慢学习者的问题常常被误判为“记不住”；苏霍姆林斯基认为真正的解法是教他们“想”——如果只逼记忆和背诵，孩子的思维会更钝。思维本身是需要教学的能力。",
      "ref": "To Children I Give My Heart, Part “The Years of Childhood”, p. 83"
    },
    {
      "id": "sk-0008",
      "type": "practice",
      "title": "用民间谜题单独训练“思维步数”",
      "source": "to-children-i-give-my-heart",
      "topics": [
        "learning-difficulties"
      ],
      "excerpt": "I started to work separately with my slow learners. I gave them simple folk riddles designed to deepen comprehension of natural numbers and to determine the interdependence of numbers... The children had to remember from two to four \"moves\" to solve each of them.",
      "cn": "实践要点：",
      "ref": "To Children I Give My Heart, Part “The Years of Childhood”, pp. 82–83"
    },
    {
      "id": "sk-0009",
      "type": "quote",
      "title": "孩子是父母道德生活的一面镜子",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "family-school"
      ],
      "excerpt": "孩子是父母道德生活的一面镜子。我曾思考过每个家庭的利和弊。好父母最有价值且毫不费力就能灌输给子女的道德品质是父母内心的善良和善待他人的能力。",
      "cn": "孩子不是靠听父母“讲道理”长大的，而是通过观察父母如何对待他人、如何生活形成最初的道德面貌。父母内心真正的善良会“毫不费力”地传递给孩子；反之，利己主义与盲目溺爱也会成为祸根。",
      "ref": "把心献给孩子（中文），《我的学生家长》"
    },
    {
      "id": "sk-0010",
      "type": "principle",
      "title": "教师只有与父母一同努力，才能带给孩子巨大幸福",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "family-school"
      ],
      "excerpt": "孩子是家庭的一面镜子。正如水滴里能映出太阳一样，父母的道德节操也会反映在孩子们的身上。因此，学校和家长们的任务是要让每一个孩子都感到幸福……教师只有与父母一同努力，才能带给孩子们巨大的幸福。",
      "cn": "学校与家庭不是“交接孩子的两端”，而是共同承担同一任务：让每个孩子感到幸福。幸福不是单靠学校或单靠家庭能完成的，教师必须与父母形成合力。",
      "ref": "把心献给孩子（中文），《我的学生家长》"
    },
    {
      "id": "sk-0011",
      "type": "practice",
      "title": "家长培训班：在孩子入学前就培训家长",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "family-school"
      ],
      "excerpt": "为了关注学龄前儿童的状况，我们成立了家长培训班，请2～6岁大儿童的家长来学习……我们力求让家长学到一定的知识和技能。家长培训学校的课程特别关注这样一个问题，就是如何教孩子思考、通过什么途径提高孩子的智力……我们还与家长们一起制订了一个关于学龄前儿童走进大自然的计划……我们还非常注重，让每一个有学龄前儿童的家庭能够营造出浓厚的读书氛围。",
      "cn": "帕夫雷什中学的“家长学校/家长培训班”在孩子入学前就已开始，面向 2–6 岁儿童的家长。内容覆盖身体、心理、智力、道德、审美发展，特别教家长如何应对孩子的提问、如何带孩子走进自然、如何营造家庭读书氛围。",
      "ref": "把心献给孩子（中文），《生活习题集里的一千道题》"
    },
    {
      "id": "sk-0012",
      "type": "principle",
      "title": "85% 学业落后与健康有关，需要家校医合力",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "family-school",
        "learning-difficulties"
      ],
      "excerpt": "经验告诉我们，大约85%成绩不及格的学生之所以学业落后，主要是因为身体状况不佳，身体有某种不适或疾病。而这些身体异常往往完全不被察觉，因此只有在父母、医生和老师的共同努力下，才能治愈这些疾病。",
      "cn": "这是“85% 学业失败与健康有关”论断的中文版本，与 On Education 中的英文表述相互印证。它说明：当孩子成绩落后时，学校不能只从教学找原因，需要父母、医生、教师三方协同排查健康。",
      "ref": "把心献给孩子（中文），《大自然是健康之源》"
    },
    {
      "id": "sk-0013",
      "type": "quote",
      "title": "学校不能完全取代家庭，教师要对缺失温暖的孩子格外留心",
      "source": "on-education",
      "topics": [
        "family-school"
      ],
      "excerpt": "School cannot fully take the place of the family, in particular a child's mother, but if a child is deprived of kind concern, warmth and care at home, we teachers must be particularly attentive to his needs.",
      "cn": "苏霍姆林斯基承认学校无法完全替代家庭，尤其是母亲的角色；正因如此，当孩子在家中缺少温暖与关怀时，教师更要格外关注他的需要。",
      "ref": "On Education (Progress Publishers, 1977), EPUB page 67（The Need to Understand the Workings of the Child's Heart）"
    },
    {
      "id": "sk-0014",
      "type": "principle",
      "title": "劳动像食物一样必不可少，要系统且完整地完成",
      "source": "on-education",
      "topics": [
        "labor-education"
      ],
      "excerpt": "Work is as essential to the individual as food, it must be regular and systematic... The body of staff at the Pavlysh school goes out of its way to ensure that the children there not only engage in work projects during their years at school but sees to it that they complete the various work projects they begin and go through all stages of the work process—from appreciation of the ultimate objective ... to profound satisfaction gleaned from its results.",
      "cn": "劳动不是临时“帮忙”或“救火”，而是像食物一样必须规律、系统。帕夫雷什中学刻意让孩子把已开始的工作做完，走完“明确目标 → 坚持完成 → 收获满足”的全过程，避免只做零散、随机的杂务。",
      "ref": "On Education (Progress Publishers, 1977), p. 199（EPUB page 200）"
    },
    {
      "id": "sk-0015",
      "type": "case",
      "title": "牵着最难教的孩子，一起去学校葡萄园劳动",
      "source": "on-education",
      "topics": [
        "labor-education",
        "learning-difficulties"
      ],
      "excerpt": "I take the most difficult and \"incorrigible\" of children by the hand, lead them to the school vineyard and say: \"Let's start working here together, with the whole collective.\" As we work away together, however \"hopeless\" a case he might have seemed, a willingness to work emerges... The day will come when the difficult and \"incorrigible\" pupil passes on the fruits of his labour to other people and experiences joy in doing so. From that moment on he is a \"man worth his salt\".",
      "cn": "面对最“难教/无可救药”的孩子，苏霍姆林斯基不是先讲道理，而是带他进入集体劳动：一起在葡萄园工作。当孩子把劳动成果送给别人并因此感到快乐时，他就开始成为“真正的人”。",
      "ref": "On Education (Progress Publishers, 1977), p. 201（EPUB page 202）"
    },
    {
      "id": "sk-0016",
      "type": "practice",
      "title": "从种麦到粮食盛典：让劳动成为可庆祝的成果",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "labor-education"
      ],
      "excerpt": "这一天留在了孩子们的记忆中。在盛典中没有关于劳动和人格的豪言壮语。重要的是盛典让孩子们激动。这是对快乐感觉的体验：我们种出粮食，我们给父母带来快乐。而一个人因自己的劳动而感到快乐，这是道德修养和高尚品格的最重要源泉。",
      "cn": "帕夫雷什的孩子不是“象征性”劳动：他们真实松土、选种、播种、收割、脱粒、磨面、烤面包，最后举办“粮食盛典”邀请父母品尝。劳动教育的关键不是口号，而是让孩子从完整劳动中体验“我能创造、我能带给他人快乐”。",
      "ref": "把心献给孩子（中文），《劳动是崇高的》"
    },
    {
      "id": "sk-0017",
      "type": "quote",
      "title": "为他人创造美而劳动的孩子，不会成为冷酷的人",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "labor-education"
      ],
      "excerpt": "生活告诉我，为了欣赏玫瑰的美丽、为了让其他人感受到欣赏美丽和创造美丽的幸福而栽种玫瑰花的孩子一定不会是残忍的、凶狠的、无耻的和冷酷的。",
      "cn": "劳动与美育在这里汇合：孩子不是为了“完成作业”而种花，而是为了让母亲、让他人欣赏到美。这种“为他人创造美”的劳动具有道德塑造力，使孩子难以变得残忍冷酷。",
      "ref": "把心献给孩子（中文），《劳动是崇高的》"
    },
    {
      "id": "sk-0018",
      "type": "method",
      "title": "用“体力 + 脑力”结合改造最懒散、最被忽视的孩子",
      "source": "on-education",
      "topics": [
        "labor-education",
        "learning-difficulties"
      ],
      "excerpt": "It is very difficult to compel pupils to exert themselves mentally, but to compel them to engage in physical work is significantly easier. A combination of manual and brain work is an all-important means of fostering love of work in the laziest and most neglected of pupils, whom parents have never made work.",
      "cn": "对家长从未让其劳动、又懒散被忽视的孩子，直接逼他“用功读书”很难；苏霍姆林斯基的方法是先让他承担一定体力劳动，再逐步让他在劳动中看到“理解与驾驭自然/事物”的智力意义，从而真正克服懒惰。",
      "ref": "On Education (Progress Publishers, 1977), p. 200（EPUB page 201）"
    },
    {
      "id": "sk-0019",
      "type": "quote",
      "title": "关注健康是教育者最重要的工作",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "health-first"
      ],
      "excerpt": "我不怕一次又一次地重复：关注健康是教育者最重要的工作。孩子们的精神生活、世界观、智力发展、知识巩固和自信取决于他们是否乐观、是否有朝气。",
      "cn": "苏霍姆林斯基把健康放在教育工作的首位：不是“先学习、再锻炼”，而是孩子的精神生活、智力发展和自信都建立在健康与朝气之上。",
      "ref": "把心献给孩子（中文），《健康，健康，还是健康》"
    },
    {
      "id": "sk-0020",
      "type": "practice",
      "title": "与家庭约定作息：户外、早睡、开窗睡、院子安睡角",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "health-first",
        "family-school"
      ],
      "excerpt": "家长们承诺会让孩子们多到户外去呼吸新鲜空气，早睡早起，开着通风窗睡觉。我和家长们商量好，在整个夏天、春末和秋初的那几个月里，要让孩子们在院子里睡觉。家长们在可以避雨的廊檐下和干草垛上设置了专门的“安睡角”……有小学生的家庭家家都要在花园里、在家门口的自留地上盖一个亭子，孩子从早春到晚秋就可以在这里看书、画画和休息。",
      "cn": "健康管理不是学校单方面规定，而是学校与家庭共同约定：多户外、早睡早起、开窗睡觉、夏季在院子安睡。学校甚至推动每个有学生的家庭建“读书亭/安睡角”，让儿童在新鲜空气中阅读和休息。",
      "ref": "把心献给孩子（中文），《健康，健康，还是健康》"
    },
    {
      "id": "sk-0021",
      "type": "method",
      "title": "新鲜空气与户外作息是健康的“灵丹妙药”",
      "source": "on-education",
      "topics": [
        "health-first"
      ],
      "excerpt": "The elixir of good health is air saturated with the phytoncides from cereals—wheat, rye, barley, buckwheat and other meadow grasses. I often used to take my pupils out into the fields and the meadows for them to breathe in the good air filled with the scent of cereals. I used to urge parents to plant hazel-nut trees under the windows of their children's bedroom; these trees fill the air with phytoncides... I also made sure that every family put up a summer shower in its garden.",
      "cn": "苏霍姆林斯基把“富含植物杀菌素的新鲜空气”称为健康灵药：常带孩子到田野草场呼吸，建议家长在儿童卧室窗外种核桃树，在院子里装夏季淋浴。健康措施往往落在家庭环境和户外作息上。",
      "ref": "On Education (Progress Publishers, 1977), EPUB page 114"
    },
    {
      "id": "sk-0022",
      "type": "case",
      "title": "光脚、户外与不怕淋雨：三四年级不再有人生病",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "health-first"
      ],
      "excerpt": "自打在“快乐学校”从事儿童教育的最初几周开始，我就非常重视体育游戏……孩子们整个夏天都光着脚走路，也不怕淋雨。我把这些看作是特别重要的体育锻炼方法。在一、二年级时有过三例感冒，到了三、四年级时已没有任何人生过病。",
      "cn": "帕夫雷什的一组实践结果：持续户外游戏、夏天光脚、不怕淋雨、冷水擦洗等锻炼后，班级感冒从一、二年级的 3 例降到三、四年级的 0 例。苏霍姆林斯基强调这不是“不怕冷”的逞强，而是长期适应与基本作息制度的结果。",
      "ref": "把心献给孩子（中文），《健康，健康，还是健康》"
    },
    {
      "id": "sk-0023",
      "type": "method",
      "title": "睡前长时间做作业，孩子会开始落后",
      "source": "on-education",
      "topics": [
        "health-first",
        "learning-difficulties"
      ],
      "excerpt": "...if a child sits at his homework for several hours before bedtime, he will start to lag behind. Passivity while a child is nominally engaged in mental work at his lessons is more often than not the result of the fact that a child spends the hours he should be out of doors—in the garden or playing snow balls—poring over books.",
      "cn": "如果孩子把本应户外活动的时间用来熬夜写作业，反而会开始落后；课堂上的“假性用功/被动”往往正是户外时间被挤占的结果。苏霍姆林斯基据此强调作业与作息安排，而不是简单增加学习时长。",
      "ref": "On Education (Progress Publishers, 1977), EPUB page 118"
    },
    {
      "id": "sk-0024",
      "type": "quote",
      "title": "自然、书籍与人中的美，能使心灵变得高尚",
      "source": "on-education",
      "topics": [
        "aesthetic-nature-education"
      ],
      "excerpt": "Our sense of the beautiful in Nature, in books and in people ennobles our minds: it helps a child to become sensitive to what is being said to him and to moral influences. The practical bias in education ... must be complemented by \"impractical arts\" otherwise that education will become too dry.",
      "cn": "苏霍姆林斯基把美育列为最重要的教育原则之一：自然、书籍和他人身上的美能提升儿童心灵的敏感性，使其更容易接受道德影响。偏重实用的教育必须用“看似无用”的艺术与美来平衡。",
      "ref": "On Education (Progress Publishers, 1977), EPUB page 36"
    },
    {
      "id": "sk-0025",
      "type": "principle",
      "title": "美的唤醒需要耐心：不是指给孩子看，而是等待他真正被触动",
      "source": "on-education",
      "topics": [
        "aesthetic-nature-education"
      ],
      "excerpt": "It is a simple undertaking to lead children out into a meadow and comment to them: \"Look how beautiful it is here!\" The children may nod in agreement but this in no way implies that they have really been struck by the beauty of the spring meadow. Sukhomlinsky recounted how it sometimes takes years before all of a sudden the all-important day and minute are at hand when ... a child's heart is suddenly aroused and filled with happiness when confronted with the beautiful. The teacher has to muster up vast reserves of patience and faith as he waits for that moment.",
      "cn": "带儿童看风景很容易，但“真正被美触动”不能靠讲解或命令。教师能做的是持续创造接触美的机会，并耐心等待那个可能数年之后才到来的时刻。",
      "ref": "On Education (Progress Publishers, 1977), EPUB page 36"
    },
    {
      "id": "sk-0026",
      "type": "practice",
      "title": "到户外去：画你眼中觉得美的东西",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "aesthetic-nature-education"
      ],
      "excerpt": "第二天，我们来到校园的一块草地上坐了下来。我给孩子们提议：“看看你们的四周。你们看到什么美，你们最喜欢什么，就画什么。”……孩子画的画和画画的过程是儿童精神生活的一部分。孩子们不只是把周围世界里的某个东西搬到纸上，而是作为美的创造者生活在这个世界上，融入这个世界里，并欣赏着这种美。",
      "cn": "帕夫雷什的绘画课不是“老师定主题、学生照画”，而是带孩子到草地上，让他们选择自己眼中觉得美的事物来画。画画因此成为儿童精神生活与自我表现的一部分，而不是单纯技巧训练。",
      "ref": "把心献给孩子（中文），《每个孩子都是画家》"
    },
    {
      "id": "sk-0027",
      "type": "quote",
      "title": "不要把孩子想象中的奇妙语言改成大人的语言",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "aesthetic-nature-education"
      ],
      "excerpt": "对孩子来讲，这并没有偏离现实，反而是鲜明、真实的，是真真实实的想象力和敏捷的思维，是巨人与火焰力量的童话共性。不要把孩子想象出的奇妙语言改成我们大人的语言。让孩子们在彼此间用自己的语言去交流……请教给孩子们比例、透视和对称的规律。这些都很好，但同时也请让孩子去自由地想象，不要破坏孩子观察世界的那种童话语言。",
      "cn": "苏霍姆林斯基并不反对教儿童绘画技法（比例、透视、对称），但他强调不要用成人写实标准去“纠正”孩子的想象表达。孩子有自己的世界观和艺术语言，需要被尊重。",
      "ref": "把心献给孩子（中文），《每个孩子都是画家》"
    },
    {
      "id": "sk-0028",
      "type": "principle",
      "title": "欣赏美只是善良情感的萌芽，必须化为积极行动",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "aesthetic-nature-education"
      ],
      "excerpt": "令我惊讶的是，孩子们对美的神往与对美的冷漠复杂地交织在一起。在与这些学生见面之前，我确实认识到欣赏美只是善良情感的萌芽。这种情感必须得到发展，并化为积极的行动力。",
      "cn": "苏霍姆林斯基观察到同一个孩子可能既被美吸引又对生物冷漠。仅“会欣赏”还不够；教育必须把审美情感发展为保护美、创造美的积极行动。",
      "ref": "把心献给孩子（中文），《爱护生物和美好事物》"
    },
    {
      "id": "sk-0029",
      "type": "quote",
      "title": "集体教育不压制个性，反而让每个孩子发展全部才能",
      "source": "on-education",
      "topics": [
        "collective-education"
      ],
      "excerpt": "Today it is impossible to educate young people outside the collective, and collective education does not in any way undermine individuality: on the contrary, precisely this type of education allows a child to develop all his abilities.",
      "cn": "针对“集体会磨平个性”的批评，苏霍姆林斯基明确反驳：脱离集体无法完成现代教育；真正的集体教育不仅不压制个性，反而是个人发展全部能力的条件。",
      "ref": "On Education (Progress Publishers, 1977), EPUB page 34"
    },
    {
      "id": "sk-0030",
      "type": "quote",
      "title": "集体只有当它能提升个人时，才成为教育力量",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "collective-education"
      ],
      "excerpt": "只有当儿童集体能有助于个人提升，能让每个人都树立起自尊心并懂得自重的时候，它才能化作一股教育力量。",
      "cn": "集体不是“管住个人”的工具，它的教育力量来自能否帮助每个成员提升、树立自尊与自重。若集体只带来从众、羞辱或压抑，就失去了教育意义。",
      "ref": "把心献给孩子（中文），《我们的集体是一个友爱的大家庭》"
    },
    {
      "id": "sk-0031",
      "type": "practice",
      "title": "集体传统：为没有过过生日的孩子庆祝生日",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "collective-education"
      ],
      "excerpt": "维佳、瓦莉娅和科利亚这三个孩子在9月份过生日。我们集体为他们过了这次生日。我们在学校食堂烤了馅饼，给小寿星们送了画儿和书。当得知科利亚家里从孩子到父母从来都没有庆祝过生日的时候，我大吃了一惊。这是这个男孩子有生以来庆祝的第一个节日。小伙伴们的关心让他激动不已。",
      "cn": "帕夫雷什的集体不是抽象组织，而是用具体传统传递关怀：给每个孩子过生日，为家庭从未庆祝过生日的孩子补上第一次节日；孩子没来上学，小伙伴晚上会去看望。这些传统让“关心他人”成为可体验的生活。",
      "ref": "把心献给孩子（中文），《我们的集体是一个友爱的大家庭》"
    },
    {
      "id": "sk-0032",
      "type": "method",
      "title": "孩子对一切冷漠时，为他匹配一位热忱的教师/同伴",
      "source": "on-education",
      "topics": [
        "collective-education",
        "learning-difficulties"
      ],
      "excerpt": "If we notice that a child is indifferent to everything, that nothing interests him, we begin to discuss who among the teachers or older pupils should be brought together with that difficult child. That is where an individual approach to a child starts... We find a way into the hearts of those children first and foremost because we are their friends in shared work.",
      "cn": "当孩子对一切无感时，苏霍姆林斯基的做法不是给他贴“冷漠”标签，而是在教师或高年级学生中寻找一个能与他建立共同劳动/共同兴趣的人。个别化教育从“为这个孩子选一个合适的大朋友”开始。",
      "ref": "On Education (Progress Publishers, 1977), EPUB page 202"
    },
    {
      "id": "sk-0033",
      "type": "principle",
      "title": "集体生活应以个人提升为宗旨",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "collective-education"
      ],
      "excerpt": "我一直希望儿童集体这个小社会单元的生活能够以个人提升为宗旨。同时，孩子们的创造力、素质、才能和天赋的发展也服从于这一宗旨。",
      "cn": "集体不是目的，个人提升才是目的。苏霍姆林斯基希望集体生活始终指向每个孩子的自尊、自爱与才能发展，而不是反过来让孩子服从集体的抽象要求。",
      "ref": "把心献给孩子（中文），《我们的集体是一个友爱的大家庭》"
    },
    {
      "id": "sk-0034",
      "type": "quote",
      "title": "没有对孩子的信念，就没有教育；没有信念就是没有爱",
      "source": "on-education",
      "topics": [
        "teacher-growth"
      ],
      "excerpt": "To teach without faith in children was in his view impossible. A lack of faith meant a lack of love. When asked what the most important thing in his life was Sukhomlinsky would always reply without a moment's hesitation, \"My love for children\".",
      "cn": "苏霍姆林斯基把“对孩子的信念”视为教师不可让渡的底线：相信孩子有力量、有能力、有“变好”的愿望。没有信念的教育在他看来不可能成立，缺少信念就是缺少爱。",
      "ref": "On Education (Progress Publishers, 1977), EPUB page 21"
    },
    {
      "id": "sk-0035",
      "type": "principle",
      "title": "教师的自由时间，是滋养创造力的根",
      "source": "on-education",
      "topics": [
        "teacher-growth"
      ],
      "excerpt": "Sukhomlinsky holds that a teacher's free time is the root which feeds the branches of his creativity. He does not demand any written reports, or any fixed duty rota. He encourages the teachers to check a representative cross section of the children's exercise books rather than spend hours poring over them.",
      "cn": "帕夫雷什的管理刻意保护教师时间：不要求书面报告、不设固定值班表、不要求逐本批改所有作业。苏霍姆林斯基认为教师创造力的根是自由时间，而不是被行政事务填满。",
      "ref": "On Education (Progress Publishers, 1977), EPUB page 20"
    },
    {
      "id": "sk-0036",
      "type": "quote",
      "title": "小学教师对孩子必须像母亲一样亲近",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "teacher-growth"
      ],
      "excerpt": "在帕夫雷什中学工作的最初几年，我一再坚信小学教师在孩子的生活中发挥着巨大的作用。他对孩子来说必须是像母亲一样亲近的人。学生对老师的信任，师生之间的相互信赖，孩子在老师眼中看到的人性思想——这些都是基本的，也是最复杂、最明智的教育规则。",
      "cn": "对低龄儿童而言，教师不是“知识传递者”的抽象角色，而应是像母亲一样可亲近的人。教育从师生信任与相互信赖开始；教师眼中的人性温度是最基本也最复杂的教育规则。",
      "ref": "把心献给孩子（中文），《学校校长》"
    },
    {
      "id": "sk-0037",
      "type": "principle",
      "title": "教师不仅是导师，也是朋友和同伴",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "teacher-growth"
      ],
      "excerpt": "培养教育者情感的重要来源是在一个友好的集体里与孩子们建立多方面的情感关系。在这个集体里教师不仅是导师，也是朋友、同伴。如果教师与学生们的见面只是在课堂上，而孩子们只有在课堂上才能感受到教师的影响，那么情感关系也会变得难以理解。",
      "cn": "教师的情感修养需要在与儿童的多样共同生活中养成：一起劳动、游戏、远足、读书。如果师生只在课堂见面，教育影响就难以进入孩子的情感世界。",
      "ref": "把心献给孩子（中文），《学校校长》"
    },
    {
      "id": "sk-0038",
      "type": "principle",
      "title": "真正的教师即使批评，也不扑灭孩子“还有目标要追”的念头",
      "source": "on-education",
      "topics": [
        "teacher-growth"
      ],
      "excerpt": "The born teacher even when reproaching a child or expressing dissatisfaction, or giving vent to his anger ... always remembers that he must not stifle the child's idea that there is a goal still to be sought after, a goal that must be attained at all costs.",
      "cn": "教师可以批评、可以不满甚至可以有情绪，但有一条底线：不能扼杀孩子心中“我还有值得追求的目标”的信念。批评若让孩子认定自己无可救药，教育就失败了。",
      "ref": "On Education (Progress Publishers, 1977), EPUB page 72"
    },
    {
      "id": "sk-0039",
      "type": "quote",
      "title": "要成为真正的儿童教育者，就必须把自己的心奉献给他们",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "love-education"
      ],
      "excerpt": "我领悟到：要成为真正的儿童教育者，就必须把自己的心奉献给他们。",
      "cn": "苏霍姆林斯基在序言中回忆教育家科尔恰克为孩子们牺牲的故事，由此领悟：真正的儿童教育不是职业表演，而是把自己的心交给孩子。",
      "ref": "把心献给孩子（中文），序言"
    },
    {
      "id": "sk-0040",
      "type": "principle",
      "title": "爱不是溺爱，而是让孩子获得幸福与自信",
      "source": "on-education",
      "topics": [
        "love-education"
      ],
      "excerpt": "It is possible to love a child to distraction, yet if a child is not getting on well at school love shown him by an adult is not going to make him happy. Love involves bestowing happiness and what happiness can be compared with self-confidence, with joy derived from success in studies?",
      "cn": "苏霍姆林斯基区分“忘乎所以的爱”与真正的教育之爱：爱不是一味宠溺，而是要帮助孩子获得真实幸福，尤其是通过成功与自信带来的快乐。只有让孩子在自己努力中感到快乐，爱才真正发生作用。",
      "ref": "On Education (Progress Publishers, 1977), EPUB page 24"
    },
    {
      "id": "sk-0041",
      "type": "quote",
      "title": "教育者的爱：厚爱 + 明智的严厉 + 父母般的严格要求",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "love-education",
        "teacher-growth"
      ],
      "excerpt": "人性是教育者最珍贵的品质之一，它是对孩子的厚爱，是结合了明智的严厉态度和父母的严格要求的爱。",
      "cn": "教育者的“人性/爱”不是无原则的温和，而是厚爱与明智严厉、父母般严格要求的结合。真正的教育爱包含要求和界限。",
      "ref": "把心献给孩子（中文），《学校校长》"
    },
    {
      "id": "sk-0042",
      "type": "method",
      "title": "察觉孩子不对劲时，不要当众立刻追问",
      "source": "on-education",
      "topics": [
        "love-education",
        "teacher-growth"
      ],
      "excerpt": "A teacher responsive to emotion will notice at once if something is not right with a child. This we can see first and foremost from a child's eyes. After realising there is something the matter with the child the sensitive teacher will not start asking questions at once. Meanwhile he will light on some means for making the child realise or feel that he, the teacher, is aware of the pupil's concern. Later questions can be asked when the other pupils are not present.",
      "cn": "敏感的教师能从孩子眼神发现异样，但不立刻当众追问，而是先用某种方式让孩子知道“老师注意到你了”，等独处时再询问。这保护了孩子的尊严与脆弱。",
      "ref": "On Education (Progress Publishers, 1977), EPUB page 64"
    },
    {
      "id": "sk-0043",
      "type": "quote",
      "title": "家中缺少疼爱的孩子，教师更要倍加关心",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "love-education"
      ],
      "excerpt": "每个人在童年时都需要得到关心和疼爱。如果孩子在冷漠无情的环境中成长，他就会变成一个对善良和美好满不在乎的人。学校无法完全取代家庭，尤其是母亲。但如果孩子在家庭里缺少疼爱、关怀和照顾，那么作为老师的我们就应该对他倍加关心。",
      "cn": "爱不是“锦上添花”，而是童年的基本需要。学校无法替代家庭，但对在家庭中缺少疼爱的孩子，教师负有补偿性关心的责任；否则孩子可能在冷漠中长大，对善良与美好满不在乎。",
      "ref": "把心献给孩子（中文），《我们的集体是一个友爱的大家庭》"
    },
    {
      "id": "sk-0044",
      "type": "principle",
      "title": "评分应只反映积极脑力劳动成果，而不是惩罚工具",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "assessment-grading"
      ],
      "excerpt": "只给脑力劳动的积极成果评分的制度已逐步在低、中、高各年级教师的工作中得以应用……在四年时间里，我有六次在学季末没给孩子成绩。家长们清楚，如果孩子的记分册里没有成绩，说明并非一切顺利。……我说服家长们，要他们决不能要求孩子取得最高分，不能把不及格视为懒惰、粗心和不认真的标志。",
      "cn": "苏霍姆林斯基主张“只给积极成果评分”：没有成果就先不给分，而不是用低分惩罚孩子。家长也被告知不能要求孩子必须得最高分，不能把不及格等同于懒惰或不认真。",
      "ref": "把心献给孩子（中文），《让孩子感受到脑力劳动的快乐和取得优异成绩的喜悦》"
    },
    {
      "id": "sk-0045",
      "type": "principle",
      "title": "绝不能拿不及格去“让家长惩罚孩子”",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "assessment-grading"
      ],
      "excerpt": "对孩子而言，老师表现出的最大的不公平是给了自己不及格的成绩，还设法要通过这样的成绩让家长惩罚自己。一旦孩子发现老师一定要把得2分的事情告诉给家长，他就会大怒，与老师和学校对立起来。脑力劳动也会成为孩子讨厌做的事情。野蛮的态度还会转嫁到其他人身上，首先是家长。",
      "cn": "如果教师给低分是为了借家长之手惩罚孩子，孩子会把学校、教师、家长和脑力劳动一起推向对立面。分数一旦变成“告状工具”，就会摧毁信任。",
      "ref": "把心献给孩子（中文），《让孩子感受到脑力劳动的快乐和取得优异成绩的喜悦》"
    },
    {
      "id": "sk-0046",
      "type": "quote",
      "title": "不要求家长在记分册签名，信任比监督更重要",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "assessment-grading",
        "family-school"
      ],
      "excerpt": "老师不要求在记分册里签名。签名是旧学校的遗留问题，也是这类学校里师生之间互不信任和相互猜忌的氛围残渣。如果班上缺乏相互间的信任，如果孩子设法想骗老师，如果分数成为大人对孩子的鞭策，那么正确的教育基础就会被毁坏。",
      "cn": "苏霍姆林斯基反对用“家长签名”监督孩子；他认为这背后是师生不信任、分数变成鞭策。真正的教育基础是信任，而不是互相防范。",
      "ref": "把心献给孩子（中文），《让孩子感受到脑力劳动的快乐和取得优异成绩的喜悦》"
    },
    {
      "id": "sk-0047",
      "type": "principle",
      "title": "不公平的低分是孩子撒谎与欺骗的温床",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "assessment-grading"
      ],
      "excerpt": "学校存在的一个最大的弊端就是孩子不诚实，欺骗老师和父母。这是不公平打2分成绩所引发的。为了向父母隐瞒自己在学校取得的坏成绩，向老师隐瞒自己的懈怠，孩子有什么诡计施展不出来呢。您对学生的不信任感越强，孩子越能在骗人这件事上花样百出，懒惰和懈怠的土壤就会愈加肥沃。懒惰是不信任的产物。",
      "cn": "孩子撒谎、隐瞒成绩，常常不是天生品行问题，而是“不公平低分+不信任”逼出来的。苏霍姆林斯基甚至说“懒惰是不信任的产物”。",
      "ref": "把心献给孩子（中文），《让孩子感受到脑力劳动的快乐和取得优异成绩的喜悦》"
    },
    {
      "id": "sk-0048",
      "type": "method",
      "title": "评价时避免“谁好谁差”的公开比较",
      "source": "on-education",
      "topics": [
        "assessment-grading",
        "learning-difficulties"
      ],
      "excerpt": "We spared the feelings of adolescent pupils by avoiding comparisons, telling pupils that some were doing well and others badly. Assessing the intellectual performance of pupils with varying abilities demands considerable tact.",
      "cn": "苏霍姆林斯基指出，对能力不同的学生进行学业评价需要高度 tact（分寸感）。他们避免公开说“谁好谁差”，因为比较会伤害学生的自尊与学习动力。",
      "ref": "On Education (Progress Publishers, 1977), EPUB page 77"
    },
    {
      "id": "sk-0049",
      "type": "quote",
      "title": "要了解孩子，就要清楚了解他的家庭",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "child-study"
      ],
      "excerpt": "为了能够很好地了解孩子们，就需要清楚地了解他们的家庭：父亲、母亲、兄弟、姐妹和祖父母等。",
      "cn": "苏霍姆林斯基把“了解家庭”作为“了解儿童”的前提。孩子不是孤立个体，他来自具体的家庭关系网络；教师若只盯着课堂表现，就难以理解孩子行为背后的原因。",
      "ref": "把心献给孩子（中文），《我的学生家长》"
    },
    {
      "id": "sk-0050",
      "type": "practice",
      "title": "开学前几周，先熟悉每一个家庭",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "child-study",
        "family-school"
      ],
      "excerpt": "在“快乐学校”开学前的几周，我熟悉了每个家庭的状况。令我感到担忧的是，在有些家庭中家长和孩子之间、父母彼此之间相处得并不融洽，也缺乏相互尊重，致使孩子无法过上幸福的生活。",
      "cn": "帕夫雷什的做法是在开学前逐户家访，系统了解每个家庭。这不只是礼貌性走访，而是为了发现哪些孩子缺少幸福与尊重，以便提前准备教育支持。",
      "ref": "把心献给孩子（中文），《我的学生家长》"
    },
    {
      "id": "sk-0051",
      "type": "quote",
      "title": "对很多教师来说，后进生是一本紧闭的书",
      "source": "on-education",
      "topics": [
        "child-study",
        "learning-difficulties"
      ],
      "excerpt": "For many, very many teachers the backward child is a tightly closed book. If a teacher cannot see into a child's heart, and understand his own particular thought patterns and way of looking at the world around him, any talk of sensitivity is futile.",
      "cn": "后进生之所以“难教”，首先因为教师没有真正读到他这本“紧闭的书”。不理解孩子独特的思维方式和世界观，任何所谓敏感与技巧都无从谈起。",
      "ref": "On Education (Progress Publishers, 1977), EPUB page 63"
    },
    {
      "id": "sk-0052",
      "type": "principle",
      "title": "真正的公平来自对每个儿童内心世界的深入了解",
      "source": "on-education",
      "topics": [
        "child-study"
      ],
      "excerpt": "Fairness is the basis for a child's trust in his educator. However, there is no such thing as abstract fairness outside individuals, outside personal interests, passions and urges. In order to be fair a teacher must have an intimate knowledge of each child's inner world.",
      "cn": "苏霍姆林斯基认为没有脱离具体个人的“抽象公平”。教师若不了解每个孩子的兴趣、情感与内心世界，就无法真正做到公平；教育就是不断加深对每个孩子的认识。",
      "ref": "On Education (Progress Publishers, 1977), EPUB page 66"
    },
    {
      "id": "sk-0053",
      "type": "principle",
      "title": "学龄前缺乏照看与信息，会熄灭好奇心",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "child-study"
      ],
      "excerpt": "我开始留意考察每个孩子从出生到上学期间的家庭环境，结果我发现了一些有意思的规律。如果孩子在学龄前无人照看，或大人未给孩子提供正常成长环境所必需的大量信息，那么孩子的大脑就会常常处在消极的状态：好奇心和求知欲消失，态度也愈加冷漠。",
      "cn": "苏霍姆林斯基通过长期观察发现：学龄前缺少照看和丰富信息，会使大脑长期处于消极状态，表现为好奇心和求知欲消失、态度冷漠。儿童研究要追溯“入学前发生了什么”。",
      "ref": "把心献给孩子（中文），《三百页〈大自然的书〉》"
    },
    {
      "id": "sk-0054",
      "type": "quote",
      "title": "会阅读，是对词句含义与美感保持敏感",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "reading-and-books"
      ],
      "excerpt": "会阅读是指对词句的含义、美感及其细微差别很敏感。只有当学生所读的词句在他的脑海中跃然纸上、栩栩如生，并呈现出周围世界变幻无穷的色彩和旋律时，才算得上是在“阅读”。",
      "cn": "苏霍姆林斯基区分“识字/流利朗读”和真正的“会阅读”。真正的阅读是词句在孩子脑中唤起形象、色彩、旋律与情感，而不只是解码文字。",
      "ref": "把心献给孩子（中文），《书在儿童精神生活中的作用》"
    },
    {
      "id": "sk-0055",
      "type": "method",
      "title": "孩子第一次读之前，先听老师和父母朗读",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "reading-and-books"
      ],
      "excerpt": "在第一次阅读之前，孩子应当听一听老师和父母是如何朗读的，感受一下艺术形象的美。不要让到大自然去“旅行”和阅读书籍脱节。如果孩子在阅读书籍之后体会不到其中词句的美，他也就看不出周围世界的美好。",
      "cn": "阅读启蒙不是直接丢书给孩子，而是先让成人大声朗读，让孩子通过听觉感受语言与艺术形象之美；阅读还应与大自然的观察和生活体验连接。",
      "ref": "把心献给孩子（中文），《书在儿童精神生活中的作用》"
    },
    {
      "id": "sk-0056",
      "type": "practice",
      "title": "建班级藏书库，让孩子反复读喜爱的书",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "reading-and-books"
      ],
      "excerpt": "在一年级的时候，我们就已经建立了一座儿童藏书库……藏书库第一部分里的每一本书，我们都读了不下10遍，但对它们的钟爱并没有因为反复阅读而稍减。",
      "cn": "帕夫雷什在一年级就建班级藏书库，精选故事、诗歌、神话等；孩子对喜爱作品会反复阅读 10 遍以上仍不觉厌倦。反复不是机械重复，而是不断从作品中获得新的精神体验。",
      "ref": "把心献给孩子（中文），《书在儿童精神生活中的作用》"
    },
    {
      "id": "sk-0057",
      "type": "quote",
      "title": "自我教育与精神生活，从读书开始",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "reading-and-books"
      ],
      "excerpt": "自我教育和个人的精神生活是从读书开始的。一直在小心翼翼地牵着学生的手、领着他前进的老师终于发现可以放开他的手对他说：“自己走吧，去学习如何生活。”……要培养一个人做到精神独立，就必须把他领进书的世界。",
      "cn": "阅读不只是学科能力，更是自我教育的基础。当孩子把书变成精神需求，教师才可能“放手”，让他走向精神独立。",
      "ref": "把心献给孩子（中文），《书在儿童精神生活中的作用》"
    },
    {
      "id": "sk-0058",
      "type": "quote",
      "title": "“思考室”只放三百本值得反复读的世界杰作",
      "source": "on-education",
      "topics": [
        "reading-and-books"
      ],
      "excerpt": "Sukhomlinsky made his pupils a library of a very different kind which he called the \"Thinking Room\". It only contains three hundred books—three hundred of the finest works of world literature, to be read and reread!",
      "cn": "帕夫雷什的“思考室”不是大而全的图书馆，而是只放 300 本精选世界文学杰作，目标不是“读过很多”，而是“反复读、读得深”。",
      "ref": "On Education (Progress Publishers, 1977), EPUB page 39"
    },
    {
      "id": "sk-0059",
      "type": "quote",
      "title": "每周两次走进大自然，是去学习思考，不是游玩",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "thinking-and-nature"
      ],
      "excerpt": "我们每周两次走进大自然，去学习思考。这并不是单纯的观察，而是去学习思考。从本质上来讲，这是一堂思维课，并非有趣的游玩，而恰恰就是上课。然而，上课也可以非常有吸引力和有趣，这能使孩子们的精神世界变得更加丰富多彩。",
      "cn": "帕夫雷什的“大自然课”不是放松式散步，而是有明确教学目的的思维课：孩子通过观察自然现象学习比较、因果与抽象思考。",
      "ref": "把心献给孩子（中文），《三百页〈大自然的书〉》"
    },
    {
      "id": "sk-0060",
      "type": "principle",
      "title": "别把孩子变成知识的仓库，要教他思考",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "thinking-and-nature",
        "learning-difficulties"
      ],
      "excerpt": "为了不让孩子变成知识的仓库，不让他们变成真理、规则和公式的储藏室，就必须教他如何思考……用记忆代替思考，用背诵代替对现象本质的清晰认识和观察，这是一大弊病，会使孩子变得迟钝，到头来还会打消他的学习兴趣。",
      "cn": "苏霍姆林斯基反对“填装知识”式教育：用记忆代替思考、用背诵代替理解，会让孩子变迟钝并丧失学习兴趣。教育的关键是教会孩子思考。",
      "ref": "把心献给孩子（中文），《三百页〈大自然的书〉》"
    },
    {
      "id": "sk-0061",
      "type": "principle",
      "title": "大自然没有自动教育魔力，必须让人思考因果",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "thinking-and-nature"
      ],
      "excerpt": "不可以夸大大自然在智力教育中的作用。如果老师认为，孩子身处大自然中就是对智力发展起到的一种强有力的刺激，那就大错特错了。大自然并没有任何能够直接影响理智、情感和意志的魔力。只有当一个人去认识大自然的时候，去深入思考因果关系的时候，大自然才会成为强大的教育资源。",
      "cn": "苏霍姆林斯基提醒：把孩子放进大自然并不会自动发展智力。只有当孩子认识自然、思考现象之间的因果关系时，大自然才成为教育资源。",
      "ref": "把心献给孩子（中文），《三百页〈大自然的书〉》"
    },
    {
      "id": "sk-0062",
      "type": "practice",
      "title": "《大自然的书》：四年 300 次观察的思维课程",
      "source": "ba-xin-xian-gei-hai-zi-zh",
      "topics": [
        "thinking-and-nature"
      ],
      "excerpt": "我悉数考虑了什么才应该成为自己学生们的思想源泉，确定了孩子们在4年里每天都要观察什么，周围世界里的什么现象会成为他们的思想源泉。于是便形成了这部300页的《大自然的书》。这是300次观察，是深深印刻在孩子们脑海中的300幅色彩鲜明的画卷。我们每周两次走进大自然，去学习思考。",
      "cn": "帕夫雷什把自然观察课程化：系统规划四年 300 次观察，每周两次“思维课”。观察对象不是随机风景，而是围绕因果、比较与思维发展的设计。",
      "ref": "把心献给孩子（中文），《三百页〈大自然的书〉》"
    },
    {
      "id": "sk-0063",
      "type": "quote",
      "title": "大自然是教育资源，唯当人理解因果关系时",
      "source": "to-children-i-give-my-heart",
      "topics": [
        "thinking-and-nature"
      ],
      "excerpt": "Nature is a powerful source of education only when the person gets to know her, is imbued with thoughts of the cause and effect relationship.",
      "cn": "这是“大自然没有自动魔力”的英文对应表述：只有当人认识自然、理解因果关系时，自然才成为强大的教育资源。",
      "ref": "To Children I Give My Heart, Part “The Years of Childhood”, p. 71"
    },
    {
      "id": "sk-0064",
      "type": "quote",
      "title": "每一节课都是用一生来备课的",
      "source": "gei-jiao-shi-de-jian-yi-zh",
      "topics": [
        "teacher-growth",
        "reading-and-books"
      ],
      "excerpt": "“对这节课，我准备了一辈子。而且，总的来说，对每一节课，我都是用终生的时间来备课的。不过，对这个课题的直接准备，或者说现场准备，只用了大约十五分钟。”",
      "cn": "一位有三十年教龄的历史教师上公开课，课后被问“花了多少时间备这节课”，他回答：直接准备只用了约十五分钟，但每一节课都是用终生时间来备的。苏霍姆林斯基由此指出，教师不抱怨没时间的奥秘在于持续读书——不是为应付明天那节课而读，而是出于内心对知识的渴求；教科书里的知识在教师的知识海洋里只是“沧海之一粟”。知识背景越宽广，教师在课堂上就越能分出注意力观察学生，而不是只盯住教材。",
      "ref": "《给教师的建议》（杜殿坤编译，教育科学出版社），(二)教师的时间从哪里来？一昼夜只有二十四小时；OCR 原PDF页段: p0000-0099 (0-based)"
    },
    {
      "id": "sk-0065",
      "type": "principle",
      "title": "评分宁可少一些，但每次都要有分量",
      "source": "gei-jiao-shi-de-jian-yi-zh",
      "topics": [
        "assessment-grading",
        "child-study"
      ],
      "excerpt": "评分宁可少一些，但是每一个评分都要有分量、有意义。",
      "cn": "苏霍姆林斯基认为，评分不应是从教学过程中孤立出来的“验收”动作，而应是建立在师生互信基础上的精细工具。他主张少打分，但每次评分都要包含学生在一段时期内的多种劳动：课堂回答、补充他人回答、书面作业、课外阅读、实际作业等。他从不凭学生一节课的表现就打分；如果学生还没有掌握，就暂时不打分，先帮助他学会，尤其不要急于给不及格分数。",
      "ref": "《给教师的建议》（杜殿坤编译，教育科学出版社），(一三)评分应当是有分量的；OCR 原PDF页段: p0000-0099 (0-based)"
    },
    {
      "id": "sk-0066",
      "type": "quote",
      "title": "儿童的智慧在他的手指尖上",
      "source": "gei-jiao-shi-de-jian-yi-zh",
      "topics": [
        "labor-education",
        "learning-difficulties"
      ],
      "excerpt": "在学校工作的几十年经验使我相信，劳动在智育中起着极其重要的作用。儿童的智慧在他的手指尖上。",
      "cn": "苏霍姆林斯基从观察中得出：双手灵巧、热爱复杂创造性劳动的孩子，往往形成聪敏好钻研的智慧。这里说的不是随便什么劳动，而是含有思想、技能、技艺和步骤间依存关系的劳动。他特别指出，学习困难儿童往往“离开事实就不能思考”，而劳动能让事物之间的关系以直观形态呈现，是帮助他们学会因果联系、发展思维的有效途径。",
      "ref": "《给教师的建议》（杜殿坤编译，教育科学出版社），(二八)用劳动的爱好来教育学生；OCR 原PDF页段: p0000-0099 (0-based)"
    },
    {
      "id": "sk-0067",
      "type": "method",
      "title": "到自然界去上'思维课'：在观察中形成概念",
      "source": "gei-jiao-shi-de-jian-yi-zh",
      "topics": [
        "thinking-and-nature",
        "child-study",
        "aesthetic-nature-education"
      ],
      "excerpt": "我努力使儿童的思维过程在生动的、形象的表象的基础上来进行，让他们在观察周围世界的时候确定各种现象的原因和后果，比较各种事物的质和特征。",
      "cn": "苏霍姆林斯基所说的“思维课”，不是带学生到户外随便散步，而是有目的地“上课”：他给学生编制了《自然界的书》300页，相当于300次观察，小学四年里每周到自然界去两次，让学生亲眼比较生物与非生物、植物与砂土、不同环境下的生命现象，鼓励他们提出“为什么”“是不是”“从哪里来”的问题，再由具体事实一步步走向“生物”“非生物”“原因”“结果”等抽象概念。他强调自然不能自动发展智力，只有教师引导儿童用思想去钻研因果联系时，自然界才能成为教育的源泉。",
      "ref": "《给教师的建议》（杜殿坤编译，教育科学出版社），(五八)“思维课”——到自然界去“旅行”；OCR 原PDF页段: p0200-0299 (0-based)"
    },
    {
      "id": "sk-0068",
      "type": "case",
      "title": "巴甫里克的'思维觉醒'：别用教科书捆住差生的智慧",
      "source": "gei-jiao-shi-de-jian-yi-zh",
      "topics": [
        "learning-difficulties",
        "child-study",
        "labor-education"
      ],
      "excerpt": "教师们把巴甫里克发展中的这一变化称为“思维的觉醒”。这一点最明显地表现在，知识的最初的源泉(客观、现实、实践、生活）受到了观察、检验和研究。",
      "cn": "巴甫里克入学后被女教师认定为“思维迟钝”，长期被要求坐在教科书前补课，越来越胆小沉默。但苏霍姆林斯基观察到，这个孩子在田野和树林里能讲出许多事物间的细微联系。升入五年级后，植物课教师让学生动手采集、观察、比较、试验，巴甫里克展现出惊人的园艺才能：他能精确嫁接、独立设计苹果树枝扦插试验，甚至发现顶部枝条成活率更高。此后他不再害怕学习，开始带着问题听课，成绩逐步赶上，最终成为农艺师。教师称这一变化为“思维的觉醒”。",
      "ref": "《给教师的建议》（杜殿坤编译，教育科学出版社），(七八)一个“差生”的“思维的觉醒”；OCR 原PDF页段: p0300-0399 (0-based)"
    },
    {
      "id": "sk-0069",
      "type": "principle",
      "title": "关心儿童的健康是教育者最重要的工作",
      "source": "gei-jiao-shi-de-jian-yi-zh",
      "topics": [
        "health-first",
        "family-school"
      ],
      "excerpt": "我想不厌其烦地再三重复：关心儿童的健康，是教育者的最重要的工作。儿童的精神生活、世界观、智力发展、知识的巩固性、对自己力量的信心，都取决于他的生命的活力和精力的充沛程度。如果把我在小学四年期间对儿童的全部关心和操劳都计算一下，那末起码有一半的操心是花在他们的健康上面的。",
      "cn": "苏霍姆林斯基把健康放在教育工作的首位，认为儿童的精神、智力、信心都以身体活力为基础。他在小学阶段实际把一半精力用于健康：与家长约定孩子多在户外活动、早睡早起、开窗睡觉，夏天在室外睡觉；坚持早操、洗淋浴、赤脚走路、滑雪和户外劳动；关注早餐营养，反对用零食刺激食欲；并指出厌烦情绪本身也会损害消化。他把健康理解为学校、家庭、作息和情感共同作用的结果。",
      "ref": "《给教师的建议》（杜殿坤编译，教育科学出版社），(八二)关心儿童的健康，是教育者的最重要的工作；OCR 原PDF页段: p0400-0499 (0-based)"
    },
    {
      "id": "sk-0070",
      "type": "quote",
      "title": "教育的核心是让学生体验到自己的尊严感",
      "source": "gei-jiao-shi-de-jian-yi-zh",
      "topics": [
        "love-education",
        "teacher-growth"
      ],
      "excerpt": "这个秘诀就是：只有教师关心学生的人的尊严感，才能使学生通过学习而受到教育。教育的核心，就其本质来说，就在于让儿童始终体验到自己的尊严感：我是一个勤奋的脑力劳动者，是祖国的好公民，是父母的好儿女，是一个有着高尚的志趣、激情和不断取得进步的完美的人。",
      "cn": "苏霍姆林斯基说，教育有一个“简单又复杂”的秘诀：教师必须先关心学生作为人的尊严感，教育才可能发生。儿童不是被动装知识的容器，师生关系每时每刻都是心灵的接触。他在实践中从不给小学生打不及格分，而是让学生重试、到课前一起思考；当学生靠自己的努力解开难题时，他让学生自己把分数写进记分册，以培养自豪感和尊严。爱护儿童对你的信任，就是关心他完满的精神生活。",
      "ref": "《给教师的建议》（杜殿坤编译，教育科学出版社），(七五)教师，要爱护儿童对你的信任；OCR 原PDF页段: p0300-0399 (0-based)"
    },
    {
      "id": "sk-0071",
      "type": "method",
      "title": "家长学校：从孩子入学前两年开始持续培训家长",
      "source": "gei-jiao-shi-de-jian-yi-zh",
      "topics": [
        "family-school",
        "child-study"
      ],
      "excerpt": "家长们在自己的孩子入学的两年以前就报名参加家长学校，在那里听课，直到他们的孩子从中学毕业为止。家长学校的心理学和教育学课程共计250学时。",
      "cn": "苏霍姆林斯基认为，只有学校和家庭“志同道合”，教育才能完整。为此他在帕夫雷什中学开办家长学校：家长在孩子入学前两年就报名，一直学到孩子中学毕业；课程按孩子年龄分五组（学前、一二年级、三四年级、五至七年级、七至十年级），每月活动两次，由校长、教导主任和有经验教师主讲，内容突出年龄心理学、个性心理学及体育、智育、德育、美育理论。他特别提醒：不要在大课上把某个儿童的家庭隐私“抖底翻出来”，敏感问题只宜个别谈话。",
      "ref": "《给教师的建议》（杜殿坤编译，教育科学出版社），(八四)我们的“家长学校”；OCR 原PDF页段: p0400-0499 (0-based)"
    },
    {
      "id": "sk-0072",
      "type": "principle",
      "title": "让每个少年都有一本心爱的书，自我教育从好书开始",
      "source": "gei-jiao-shi-de-jian-yi-zh",
      "topics": [
        "reading-and-books"
      ],
      "excerpt": "我努力做到使每一个少年都有一本心爱的书，使他反复阅读、反复思考这本书。这样做并不是为了他必须把读过的东西记住并且用来回答教师的问题，而是为了使他为自己的命运而感到激动。我坚定地相信，少年的自我教育是从读一本好书开始的，并且表现为他能用最高的尺度——那些英勇的、忠于崇高思想的人们的生活来衡量自己。",
      "cn": "苏霍姆林斯基把阅览室命名为“思考之室”，强调真正的阅读不是为应付识记，而是吸引理智与心灵、促使少年认识自己和自己的未来。他特别看重名人传记：少年用英雄人物的生活作为尺度衡量自己，就是自我教育的开端。他并不急于追问学生“你读后有什么感想”，而是让书先在心里发酵；如果一个少年还没有一本反复读、反复想的心爱之书，教育者就还没有找到通往他心灵的小路。",
      "ref": "《给教师的建议》（杜殿坤编译，教育科学出版社），(八三)“思考之室”——我们的阅览室；OCR 原PDF页段: p0400-0499 (0-based)"
    },
    {
      "id": "sk-0073",
      "type": "quote",
      "title": "每个孩子天性都是诗人，要让诗的琴弦响起来",
      "source": "gei-jiao-shi-de-jian-yi-zh",
      "topics": [
        "aesthetic-nature-education",
        "thinking-and-nature"
      ],
      "excerpt": "每一个孩子就其天性来说都是诗人，但是，要让他心里的诗的琴弦响起来，要打开他的创作的泉源，就必须教给他观察和发觉各种事物和现象之间的众多的关系。",
      "cn": "苏霍姆林斯基带六岁学前儿童每周到果园、树林、河岸“读大自然这本书”，让学生把词语和鲜明画面、情感色彩联系起来。他认为儿童本来就会用自己的语言创造故事，但需要成人教他观察事物之间的众多联系；例如面对一棵开花的树，当儿童发现阳光、花瓣、蜜蜂、树枝、蝴蝶之间的几十种联系后，他就能编出成千上万个独特的故事。学生自编的《花瓣儿和花朵》等故事，就是这种“诗的琴弦”被拨响的证据。",
      "ref": "《给教师的建议》（杜殿坤编译，教育科学出版社），(五六)让孩子们心里的诗的琴弦响起来；OCR 原PDF页段: p0100-0199 (0-based)"
    }
  ]
};
